[[short-id-for-section]]
=== Darwin Core standard and biological survey data

The https://dwc.tdwg.org/[+++Darwin Core (DwC) standard+++] is a
community-maintained biodiversity information standard. The primary goal
of DwC is to support biodiversity informatics by making data
interoperable and reusable across various platforms and applications.
DwC provides a set of terms, definitions, and guidelines designed to
facilitate the exchange of biological data. DwC *terms* are used to
describe and share biodiversity data. Each term has an accepted
definition accompanied by comment(s),a usage example (for example, see
https://eco.tdwg.org/terms/#eco:verbatimTargetScope[_+++verbatimTargetScope+++_]
and
https://eco.tdwg.org/terms/#eco:protocolNames[_+++protocolNames+++_]),
and in some cases contains controlled vocabulariesfootnote:[A list of
accepted values that can be used for the term]. Populating DwC terms
with information from a particular dataset is called *mapping*. Use of
the standard can help reduce errors and inconsistencies in data, enhance
data discoverability, and facilitate data reuse. DwC includes
standardized terms for describing species occurrences and biodiversity
sampling efforts, including terms for methodology, location, date,
taxonomy, and other relevant attributes. DwC *extensions* provide
additional terms and properties for specific types of biodiversity data
enabling researchers to capture a broader range of information tailored
to particular needs, such as data on ecological interactions, genetic
sequences, or sampling events.

In a Darwin Core context, biological survey data are best captured as
https://dwc.tdwg.org/list/#dwc_Event[+++Events+++], where time- and
space-specific detection are documented centrally and separately from
the list of species recorded in each event. Historically, DwC evolved
from collections to other biodiversity data contexts, and until recently
struggled to effectively capture more complex data like biological
surveys. Specifically, detailed information about sampling methods and
protocols, scope, and completeness were captured in an unstructured
manner relegated largely to verbatim text fields such as
https://dwc.tdwg.org/terms/#dwc:samplingProtocol[+++samplingProtocol+++]
and
https://dwc.tdwg.org/terms/#dwc:samplingEffort[+++samplingEffort+++].
The https://eco.tdwg.org/[+++Humboldt Extension for Biological
Inventories+++] (HE), an extension to the DwC event core, provides data
publishers with a means by which to share biological inventory data in a
structured manner, increasing the findability of datasets, and thereby
improving chances of dataset re-use. The extension added 55 terms to the
DwC Event class vocabulary by which to capture components of survey
design previously lost as unstructured metadata.
