== Resource metadata

[IMPORTANT] 
====
Resource metadata information should be saved to the DwC-A metafile.
====

*Resource metadata* provides project- and/or dataset- level information
for potential data users to understand the context of the dataset. GBIF
uses https://eml.ecoinformatics.org/[Ecological Metadata Language]
(EML), a metadata standard administered and maintained by
https://knb.ecoinformatics.org/[The Knowledge Network for Biocomplexity]
that records information about ecological datasets in a series of
modular and extensible XML document types. Each Darwin Core Archive
should include a resource metadata (EML file) written in XML format.

GBIF currently requires 8 and strongly recommends 1 dataset-level
metadata terms (see
https://www.gbif.org/data-quality-requirements-sampling-events[Data
Quality Requirements for Sampling Events] for more information; Table
4):

* *_title:_* The title under which the dataset will be published at
gbif.org. The title should be brief, but descriptive, characterizing the
dataset in an international context and distinguishing it from similar
datasets in other institutions. +
* *_description:_* An English language text, describing the dataset.
This may include a longer version of title, a description of geographic,
temporal and taxonomic scope of the dataset, methodology and purpose of
the underlying data compilation (e.g. protected habitat surveillance,
faunistic inventory, deep sea trawl data), relevant literature
references, and any other information you consider relevant to
characterize the dataset. Essentially a resource abstract. +
* *_publishing organization:_* The title of the institution or
organization that will be listed as the data publisher at gbif.org. The
publishing organization is the institution which holds or owns the
dataset and is in charge of its contents and maintenance. +
* *_type:_* The type of dataset aligns with the DwC core implemented.
Type for survey and monitoring datasets will be `samplingEvent'. +
* *_license:_* A machine-readable statement of the rights attached to
the published dataset. GBIF supports the following Creative Commons
licenses: CC0, CC BY, and CC BY-NC (see https://www.gbif.org/terms). +
* *_contact(s):_* Contact information for the person or institution to
contact with questions about the use and/or interpretation of the
dataset. This information is required to ensure the possibility of
communication about the dataset. Minimum required information is contact
name and email address. +
* *_creator(s):_* Contact information for the creator of the dataset. +
* *_metadata provider(s):_* Contact information for the author(s) of the
dataset metadata. Minimum required information is contact name and email
address. +
* *_citation:_* A text specifying how your dataset should be cited in
publications that make use of your data. If no suggested citation is
specified, GBIF will automatically supply a standard format citation
that includes the dataset name, the name of the publishing institution,
the date of the download, and a reference to gbif.org.

See the
https://ipt.gbif.org/manual/en/ipt/latest/gbif-metadata-profile[GBIF
Metadata Profile – How-to Guide] for comprehensive guidelines and list
of available terms for resource metadata <<GBIF2011>>.

<<<
