== Resource metadata

[IMPORTANT] 
====
Resource metadata information should be saved to the DwC-A `metafile`.
====

*Resource metadata* provides project- and/or dataset-level information for potential data users to understand the context of a dataset. GBIF's metadata schema is based https://eml.ecoinformatics.org/[Ecological Metadata Language] (EML), a metadata standard administered and maintained by https://knb.ecoinformatics.org/[The Knowledge Network for Biocomplexity], which captures information about an ecological dataset in a series of modular and extensible XML documents. Each Darwin Core Archive must include a resource metadata written in XML format: `eml.xml`.

GBIF currently requires 8 dataset-level metadata terms (see https://www.gbif.org/data-quality-requirements-sampling-events[Data Quality Requirements for Sampling Events] for more information):

* *_title:_* This is the title under which the dataset will be published at https://www.gbif.org/[gbif.org]. The title should be brief, but long enough and descriptive enough to characterize the dataset in an international context and distinguish it from similar datasets from other institutions. +
* *_description:_* A brief, textual description of the dataset. This may include an extended version of the title, a description of the geographic, temporal and taxonomic scope(s) of the dataset, information about the methodology implemented and purpose of the underlying data compilation (e.g. protected habitat surveillance, faunistic inventory, deep sea trawl data, survey steps or gear used), relevant literature references, and any other information you consider relevant to characterize the dataset. This is, in essence, a resource abstract. +
* *_publishing organization:_* The name of the institution or organization that will be listed as the data publisher at https://www.gbif.org/[gbif.org]. The publishing organization is the institution which holds or owns the dataset and is in charge of its contents and maintenance. +
* *_type:_* Type refers to the dataset structure reflecting the level of detail captured in the dataset. In GBIF, four types of datasets are currently accepted: sampling event, occurrence, checklist, and metadata. Type for survey and monitoring datasets is `samplingEvent`. +
* *_license:_* A machine-readable statement of the rights and intended use attached to the published dataset. GBIF supports the following Creative Commons
categories: CC0, CC BY, and CC BY-NC (see https://www.gbif.org/terms[GBIF Terms of use]). +
* *_contact(s):_* The contact field contains contact information for a dataset. This is the person or institution to reach out to with questions about the use or interpretation of a dataset. The information for at least one contact is required to ensure the possibility of communication about the dataset. Minimum required information for resource each contact is name and email address. +
* *_creator(s):_* A resource creator is the person(s) or organization(s) responsible for creating a resource. Contact information for at least one dataset creator is required. The minimum required information for each dataset creator includes name and email address for at least one contact. +
* *_metadata provider(s):_* The metadata provider is the person or organization responsible for providing documentation for a resource. At least one metadata provider must be listed. The minimum required information for each metadata provider is name and email address. 

These 8 terms must be populated in order to successfully publish a dataset to GBIF. See the https://ipt.gbif.org/manual/en/ipt/latest/gbif-metadata-profile[GBIF Metadata Profile – How-to Guide] for comprehensive guidelines and a list of all available resource metadata terms <<GBIF2011>>.

<<<
