[[survey-event-data:-capturing-the-context-of-biological-surveys]]
== Survey Event data: capturing the context of biological surveys and monitoring data

[IMPORTANT] 
====
The contextual information about survey Events should be saved to the DwC-A `event` table.
====

This section will guide you through the process of mapping Event-level data specifically related to survey structure, location, protocols, scopes, and effort. 

[NOTE] 
.About DwC terms in this document

==== 

Each term in this document is linked with its respective term https://www.w3.org/International/O-URL-and-ident.html[internationalized resource identifier (IRI)] alias (ex., term:eco[eco:protocolNames]). Always use these links to refer to the definition, comments, and examples provided when populating a term. 

The terms to be used to describe Event-level information are a combination of Darwin Core Event class and Humboldt Extension terms:

* A comprehensive list of Darwin Core Event class terms is available on the https://rs.gbif.org/core/dwc_event_2024-02-19.xml[Darwin Core Event] page in the GBIF Registry of Schemas. +
* The full suite of Humboldt extension terms is available on the https://rs.gbif.org/extension/eco/Humboldt_2024-04-16.xml[Humboldt Ecological Inventories^] page in the GBIF Registry of Schemas and the https://eco.tdwg.org/terms/[Humboldt Extension Quick Reference Guide].
====


****
[discrete]
==== Data mapping tips

Survey Event data should be saved to the DwC-A `event` table. This includes DwC Event terms (any term preceded by `dwc`, e.g., term:dwc[dwc:eventID]) and Humboldt extension terms (any term preceded by `eco`, e.g., term:eco[eco:protocolNames]).

Populate all terms for which information is available. 

<<pairedTerms, *Paired terms*>> must be populated together. These terms are designed to offer data publishers some level of flexibility in reporting data. Paired terms are most common in terms available for reporting a variable value and associated unit of measure (for example, term:dwc[dwc:sampleSizeValue] and term:dwc[dwc:sampleSizeUnit]). 

*No data, missing data, and data values of `0`*

  * Cells with a value of `0` (zero) should be explicitly populated as `0`.
  * Cells with missing data or `NULL` values should be left empty. 
  * Terms for which there is `no data` to share at any hierarchical level can be excluded from the data table.

*Populating terms across Event levels (e.g., from parent Event to child Event)* 

* Each Event can have its own set of attributes and measurements which can be captured using the Humboldt and/or other extension(s) and be unambiguously linked to the corresponding Event through the appropriate term:dwc[dwc:eventID]s. +
* *_Terms should contain data clearly (explicitly) reported at every Event level in the hierarchy to which they directly apply._* This means that when publishing a data export, +
** a child Event must *not* be assumed to be inherit the value of any property of any of its parent Event(s). If a value is in common between a child Event and its parent Event, the value should be reported explicitly in both Event records (see Section 3.2.2 Principle of applicability in https://eco.tdwg.org/hierarchy/#322-principle-of-applicability[Properties of hierarchical events in the Humboldt Extension for Ecological Inventories^]). +
** a parent Event should *not* be populated by deriving or summarizing information from child Events; rather, fields should be explicitly populated with information directly appropriate to the nature and level of the Event itself (see Section 3.2.3 Principle of non-derivation in https://eco.tdwg.org/hierarchy/#323-principle-of-non-derivation[Properties of hierarchical events in the Humboldt Extension for Ecological Inventories^]). 

Refer to https://eco.tdwg.org/hierarchy/[Properties of hierarchical events in the Humboldt Extension for Ecological Inventories^] for more guidance in populating Humboldt extension terms across Event levels.
****

=== Survey design

<<surveyDesign, Survey design>> is the strategy underpinning a biological survey. It details the sampling method implemented in a particular survey including how any stations, plots, traps, sensors, and/or transects are positioned. Historically, only 2 terms were available to structure and relate different levels of survey design in a dataset: term:dwc[dwc:eventID] and term:dwc[dwc:parentEventID]. One additional Darwin Core Event term, term:dwc[dwc:fieldNumber], provided a means by which to relate a sampling Event with a dataset- or project-specific field number. The Humboldt extension provides an additional 2 terms (term:eco[eco:siteCount] and term:eco[eco:siteNestingDescription]) to better support complex or nested survey designs. 

[NOTE]
.*Event data in GBIF*
====
* Any dataset to be published using the DwC Event core must have at least one Event record. +
* Each term:dwc[dwc:eventID] in a dataset must be unique within the dataset. Use of a persistent globally unique identifier (GUID) is recommended to ensure that the GUID is unique across all datasets. A unique term:dwc[dwc:eventID] should be reused between datasets where appropriate (for example, where data collected during the same sampling event are published as multiple datasets). See
https://assets.ctfassets.net/uo17ejk9rkwj/8aIUAbLo0oycyMiM2IKUS/363edf7ab4558460cfe1ef140567450f/persistent_identifiers_guide_en_v1.pdf[A
Beginner’s Guide to Persistent Identifiers^] for guidance in creating persistent identifiers. Note that your field numbers should be reported using term:dwc[dwc:fieldNumber]. +
* An Event is not required to have associated organism Occurrence data. If organism Occurrence or non-detection data are available, they will be linked via the term:dwc[dwc:eventID] in the `occurrence` table using the 
https://rs.gbif.org/core/dwc_occurrence_2024-02-23.xml[occurrence extension^]. +
* Other DwC Event extensions, including https://rs.gbif.org/core/dwc_occurrence_2024-02-23.xml[occurrence], https://rs.gbif.org/extension/obis/extended_measurement_or_fact_2023-08-28.xml[extended
measurement or fact^], and https://rs.gbif.org/extension/gbif/1.0/releve_2016-05-10.xml[relevé^] extensions, can be linked to any appropriate Event via the term:dwc[dwc:eventID].
====

*Non-nested datasets*

* Each Event in a non-nested dataset must be assigned a unique term:dwc[dwc:eventID]. +
* Non-nested datasets will not have a term:dwc[dwc:parentEventID]. 


*Nested datasets*

Nested hierarchies are established by relating a child Event to a parent Event through the child Event´s term:dwc[dwc:parentEventID]. As such, these more complex datasets require use of both term:dwc[dwc:eventID] and term:dwc[dwc:parentEventID].

* Each Event in a nested dataset must have a unique term:dwc[dwc:eventID]. +
* Each child Event should include the term:dwc[dwc:parentEventID] of its parent in term:dwc[dwc:parentEventID].

In practice, this means that the parent and the child will each have a unique term:dwc[dwc:eventID]. To create the parent-child relationship, the parent Event's term:dwc[dwc:eventID] will be also be reported as the child Event's term:dwc[dwc:parentEventID].

[caption=]
.Simple example illustrating how a parent-child relationship between two nested Events would look using Event identifiers.
|===
| term:dwc[dwc:parentEventID] | term:dwc[dwc:eventID]
|
| event:site-1

| event:site-1
| event:site-1:t1

|===

In addition to Event and parent Event identifiers:

* *Site count and site nesting description:* Nested datasets should include the total number of sites sampled in term:eco[eco:siteCount] and provide a textual description of the survey design or site sampling structure using term:eco[eco:siteNestingDescription] for each parent Event for which the information is available. +
* *Field number:* If the survey data include a field number for a specific Event, this should be shared using term:dwc[dwc:fieldNumber].

[caption=]
.Event hierarchy terms, their recommended usage (status), and example data entries.
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Required
|term:dwc[dwc:eventID]
|`survey2022_a-2`

|Required for nested datasets
|term:dwc[dwc:parentEventID]
|`survey2022`

.2+|Recommended
|term:eco[eco:siteCount]
|`75`

|term:eco[eco:siteNestingDescription]
|`25 survey sites each with 3 1m2 quadrats`

|Share if available
|term:dwc[dwc:fieldNumber] 
|`RV Sol 87-03-08`
|===

=== Survey site

An Event <<site, *site*>> is the location at which observations are made or samples and/or measurements are taken. Sharing thorough information about a sampling Event site, including description, locality, and vegetative cover provides critical context to potential data users about conditions in which a survey was conducted. Information about the location of each survey site includes best-practice georeferences, site description (locality name, habitat type, microhabitat), and environmental data (e.g., physical parameters, vegetarian, water quality) should be populated at every Event level. 

NOTE: The Darwin Core site terms listed in this section are not comprehensive. Explore all http://purl.org/dc/terms/Location[Darwin Core Location class terms^] and the https://eco.tdwg.org/terms/#site[Humboldt Extension site terms^].

==== Site description

Additional context about a survey Event site can be provided through myriad terms for every Event level that the information is available, including:

* *Site names:* individual sampling Event site names can be reported using term:eco[eco:verbatimSiteNames]. A concatenated list of site names can be provided at higher Event levels with values separated using a pipe separator, `|`.  +
* *Habitat:* feported habitat at a sampling Event site should be recorded in term:dwc[dwc:habitat]. A concatenated list of habitats can be provided at higher Event levels with values separated using a pipe separator, `|`. Use of a controlled vocabulary is recommended. Note that a single controlled vocabulary does not exist for this term yet but attempts to classify have been and continue to be made (for example, see <<Keith2020>> or <<Campbell2021>>).  +
* *Weather:* reported weather during a sampling Event should be reported using term:eco[eco:reportedWeather]. If you have detailed weather data (e.g., weather station or data logger produced data) archived elsewhere, you may provide a link here. +
* *Extreme conditions:* reported extreme conditions at a survey site at the time of the sampling Event should be recorded using term:eco[eco:reportedExtremeConditions]. +
* *Verbatim site description:* verbatim comments (e.g., the original textual description) about a site or sites should be recorded in term:eco[eco:verbatimSiteDescriptions].

These terms should be populated at every Event level for which the information is accurate. 

[caption=]
.General event site terms, their recommended usage (status), and example data entries
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
.5+|Share if available
|term:eco[eco:verbatimSiteNames]
|`Trap_18\|Trap_27\|Trap_54\|Trap_96`, `Annala \| Kumpula`

|term:dwc[dwc:habitat]
|`Ephemeral wetland`

|term:eco[eco:reportedWeather]
|`{"minimumTemperatureInDegreesFahrenheit": 18, "maximumTemperatureInDegreesFahrenheit": 32}`

|term:eco[eco:reportedExtremeConditions]
|`Site flooded`

|term:eco[eco:verbatimSiteDescriptions]
|`Coastal sand dunes at dry oak forest edge. Vegetation: Ammophila arenaria, Betula pendula, Leymus arenarius, Pinus sylvestris`
|===

==== Site locality

The geographic location and extent of each survey Event site should be provided. Historically, five terms are strongly recommended for Event datasets in GBIF:

* *Location ID:* a unique identifier for each sampling Event site should be shared in term:dwc[dwc:locationID]. If a site is visited repeated (as in long-term monitoring and other repeated survey efforts), term:dwc[dwc:locationID] should be consistent across Events within a dataset and across datasets in situations where the same survey sites are surveyed in other datasets. +
* *Country code:* the ISO two letter code for the country, region, or economy in which the survey takes place should be provided in term:dwc[dwc:countryCode]. +
* *Latitude-Longitude:* The decimal latitude and longitude and geodetic datum location of each Event site should be reported in term:dwc[dwc:decimalLatitude], term:dwc[dwc:decimalLongitude], and term:dwc[dwc:geodeticDatum]. All three terms should be populated together.
** If geographic coordinates are not in decimal latitude and decimal longitude format, use the terms term:dwc[dwc:verbatimLatitude], term:dwc[dwc:verbatimLongitude], and term:dwc[dwc:verbatimCoordinateSystem] to report geographic locality instead. +
** Note that this is a minimum recommendation and does not make data fit for the maximum number of purposes. It is highly recommended to provide georeference information that follow best practices.

==== Survey site area

Reporting additional information about the targeted area and the area(s) actually sampled during a survey is recommended to provide greater context about the geospatial scope of a survey. The Humboldt extension includes two sets of paired terms to report survey area of an Event: _geospatial scope_ terms and _total area sampled_ terms. 

* *_Geospatial scope_* terms (term:eco[eco:geospatialScopeAreaValue] and term:eco[eco:geospatialScopeAreaUnit]) define the geospatial scope or extent of a survey or sampling Event. Geospatial scope terms can be applied at any Event level and should report the entire area considered for the survey.

* *_Total area sampled_* terms (term:eco[eco:totalAreaSampledValue] and term:eco[eco:totalAreaSampledUnit]) report the area sampled during an Event. Total area sampled terms can be populated at any Event level but are most commonly applied at lower Event levels to, for example, capture the survey extent of a single plot or the cummulative area surveyed in a series of plots within a site. 

In *non-nested event datasets*, geospatial scope terms and total area sampled terms may contain the same values. 

In *nested datasets*, geospatial scope terms will be equal to or greater than the area values shared in total area sampled terms. See Box 2 for an example.

*_If the surveyed unit is not an area_* (e.g., `km²` or `m²`), term:dwc[dwc:sampleSizeValue] and term:dwc[dwc:sampleSizeUnit] should be used instead. Examples include:
* point locations (such as a sensor or trap),
* distances (such as transect lengths), and
* volumetric measures (such as a filtered volume of water in a zooplankton haul).

****
[discrete]
==== Box 2. Biowide project example
Consider the https://www.gbif.org/dataset/cd4eb3ec-0a18-42b4-bda4-155716ddd7b1[Biowide project^] which surveyed 130 40×40m plots across Denmark. 

Here, the project-level parent Event would report the full geographic extent of Denmark: term:eco[eco:geospatialScopeAreaValue] = `42934` and term:eco[eco:geospatialScopeAreaUnit] = `km²` and the sum of sampled areas: term:eco[eco:totalAreaSampledValue] = `208000` and term:eco[eco:totalAreaSampledUnit] = `m²`. 

For each of the 130 associated child Events representing the individual plots, term:eco[eco:geospatialScopeAreaValue] and term:eco[eco:geospatialScopeAreaUnit] would be left empty because geospatialScope was a characteristic of the higher-level survey design not the individual survey site visits. For the plots, the area of the site would be term:eco[eco:totalAreaSampledValue] = `1600` and term:eco[eco:totalAreaSampledUnit] = `m²`.
****


==== Additional survey site information

* **Survey site geometry:** If available, the geometry of a survey site area should be shared using term:dwc[dwc:footprintWKT] and term:dwc[dwc:footprintSRS]. +
* **Verbatim site location information:** A more general text description of the site location, if available, can be shared using term:dwc[dwc:locality].

[caption=""]
.Event site geographic locality and scope terms and their recommended usage (status), namespace abbreviation, and example data entries.
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
.11+|Recommended
|*term:dwc[dwc:locationID*]
|`Trap_138`

|term:dwc[dwc:countryCode]
|`SE`

|term:dwc[dwc:decimalLatitude]
|`59.3168`

|term:dwc[dwc:decimalLongitude]
|`18.0627`

|term:dwc[dwc:geodeticDatum]
|`epsg:4326`

|term:eco[eco:geospatialScopeAreaValue]
|`580000`

|term:eco[eco:geospatialScopeAreaUnit]
|`km²`

|term:eco[eco:totalAreaSampledValue]
|`1600`

|term:eco[eco:totalAreaSampledUnit]
|`m²`

|term:dwc[dwc:sampleSizeValue]
|`200`

|term:dwc[dwc:sampleSizeUnit]
|`m³`

.3+|Share if available
|term:dwc[dwc:footprintWKT]
|`POLYGON \((10 20, 11 20, 11 21, 10 21, 10 20))`

|term:dwc[dwc:footprintSRS]
|`epsg:4326`

|term:dwc[dwc:locality] 
|`Agriculture site, Kongskilde Friluftsgård, Zealand`
|===

==== Vegetation cover

If vegetation cover data are available for a site (for example, if a relevé was conducted or if a verbatim site description was recorded), it can be reported in three ways:

* *Verbatim vegetation cover:* a verbatim description of vegetation cover can be captured in term:eco[eco:verbatimSiteDescriptions]. +
* *Percent vegetation cover:* simple percent vegetation cover can be recorded as structured data using the https://rs.gbif.org/extension/obis/extended_measurement_or_fact_2023-08-28.xml[extended
measurement or fact extension^]. Data reported using emof should be linked to the appropriate Event using term:dwc:[dwc:eventID]. See the 'link:#extended-measurement-or-fact-emof-extension[Extended measurement or fact (eMoF) extension]' section for details on using the extension. +
* *Vegetation plot survey:* vegetation plot survey information can be reported using the https://rs.gbif.org/extension/gbif/1.0/releve_2016-05-10.xml[relevé extension^]. Data from individual relevé's should be linked to the appropriate Event using term:dwc:[dwc:eventID]. See the 'link:#relevé-extension[Relevé extension]' section for details on using the extension.

There is no single best method of reporting vegetation cover information for a site, although it is recommended to choose the most explicit method possible based on the type of information avilable. 

If vegetation cover is reported using one of the three methods described above, then term:eco[eco:isVegetationCoverReported] = `true`; otherwise, term:eco[eco:isVegetationCoverReported] = `false`.

=== Survey date and time

Complete and accurate reporting of the temporal scope of a survey is crucial to asserting Event structure and providing key contextual information about sampling conditions.

*Event date, time, and duration*

Each Event should report a date or date range in term:dwc[dwc:eventDate] regardless of its hierarchical level. *Nested datasets* should, at the parent Event level, report a date range encompassing all survey dates.

The time and duration of each Event should be reported using term:dwc[dwc:eventTime] and the paired terms term:eco[eco:eventDurationValue] and term:eco[eco:eventDurationUnit] respectively.

Refer to GBIF’s technical documentation on https://techdocs.gbif.org/en/data-processing/temporal-interpretation[date and time interpretation^] for more guidance on reporting event dates and times.

[caption=""]
.Event date and temporal scope terms, their recommended usage (status), and example data entries.
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Required
|term:dwc[dwc:eventDate]
|`2018-08-29`

.3+|Recommended
|term:dwc[dwc:eventTime]
|`08:00Z`

|term:eco[eco:eventDurationValue]
|`1`

|term:eco[eco:eventDurationUnit]
|`hour`
|===

=== Methodology or sampling protocol

<<samplingProtocol, *Sampling protocols*>> provide the details of how a survey was conducted. Protocol information should be a detailed, step-wise description outlining all the details about the data collection process necessary to ensure repeatibility of the implemented methodology. Clear communication of a sampling protocol or the method(s) implemented during a survey or monitoring effort guarantees consistency, accuracy, and reliability in the data collected. This information further ensures reproducibility and reusability of a dataset, and facilitates data aggregation, integration, and subsequent analysis.


[IMPORTANT]
====
Sampling protocol terms should be populated at every Event level possible as inheritance in either direction should not be assumed or inferred between Event levels.
====

==== Event type

Biological survey Event data can result from a wide variety of effort types (e.g., Bioblitzes, inventories, monitoring schemas, expeditions). The nature of the survey Event should be reported using term:dwc[dwc:eventType].

****
[discrete]
==== Identifying Event type

term:dwc[dwc:eventType] should provide a high level overview or name of the type of survey but should not be so specific as to overlap with sampling protocol. There is no single, standardized vocabulary for term:dwc[dwc:eventType]. If your organization or community has a controlled vocabulary, it is recommended to apply terms from that. Otherwise, you can refer to the common event types below for guidance. More than one term may apply to an Event; choose the term that fits most closely.

* *Project*: Projects are structured initiatives with an explicitly stated objective or suite of objectives and with clear targets, timelines, and deliverables. Projects typically are linked to non-biological information identifying participating organizations and people (agents), funding agencies, and other high-level administrative information. Biological sampling may only be one facet of a project’s scope. `Project` as an term:dwc[dwc:eventType] is typically most appropriate only at the highest Event level in a nested dataset. +
* *Expedition*: An expedition is an organized information gathering venture that inherently includes multiple sampling Events and event types. Expeditions may include multiple taxonomic and/organismal scopes, any number of documented sampling protocols, and varying degrees of complexity in survey design. `Expedition` as an term:dwc[dwc:eventType] is typically most appropriate at higher Event levels in nested hierarchies. +
* *Survey*: A survey is a broad but systematic effort to collect information about the biological organisms in a specific area at a given time. Surveys typically included at least one documented protocol and may or may not have an explicitly defined taxonomic and/or organismal scope. `Survey` is the most general Event type term and can be applied as an term:dwc[dwc:eventType] at any Event level. +
* *Inventory*: An inventory is a comprehensive, focused survey of the taxa present in a specific area over an explicit period of time. Inventories typically have an explicit taxonomic and/or organismal scope and a well-defined protocol. `Inventory` is typically most appropriate as an term:dwc[dwc:eventType] at lower Event levels in nested hierarchies. +
* *Bioblitz*: A bioblitz is a survey Event aimed at finding and identifying as many species as possible in a specific area over a (typically) short, contiguous period of time. Bioblitzes often include participants (agents) with a wide range of backgrounds and levels of expertise in biodiversity sciences including
formal biologists as well as the broader, general public. `Bioblitz` as an term:dwc[dwc:eventType] is typically most appropriate at lower Event levels in nested hierarchies. +
* *Site visit*: A site visit is a single survey, inventory, or sampling at a pre-established geographic location at a discrete time. `Site visit` as an term:dwc[dwc:eventType] is typically most appropriate at the lowest event level in a nested hierarchy. +
* *Sample*: A survey event denoted by the specific act of collecting physical samples resulting in material specimen. A sampling term:dwc[dwc:eventType] is a specific implementation of a survey Event. 'Sample' as an term:dwc[dwc:eventType] is typically most appropriate at lower (child) Event levels in a nested hierarchy. +
* *Sensor*: The detection of an Occurrence (or a group of related occurrences such as a time series or group of organisms) by means of a sensor. A sensor may be static (e.g., camera traps) or mobile (e.g., drones) external to an organism, or it may be attached to an organism (e.g. radio collar). 'Sensor' as an term:dwc[dwc:eventType] is typically most appropriate at lower (child) Event levels in a nested hierarchy.
****

*`Inventory` Event types*

* If term:dwc[dwc:eventType] = `inventory`, the type(s) of search implemented (e.g., restricted search, open search, opportunistic search, trap or sample, compilation) must be reported in term:eco[eco:inventoryTypes]. +
* If term:eco[eco:inventoryTypes] = `compilation`, the compilation type should be reported using term:eco[eco:compilationTypes] and data sources listed in term:eco[eco:compilationSourceTypes].
** A *[[compilation]]* is a summary inventory resulting from the combination of multiple existing inventories (as described in <<Guralnick2018>>). Compilations are aggregates of multiple studies, and may combine surveys employing different protocols, processes, and observers, often with variable reporting of the methods employed or other compiled data sources and literature searches.

[caption=""]
.Event type terms, their recommended usage (status), and example data entries
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Recommended |term:dwc[dwc:eventType]
|`Inventory`

.3+|Recommended if applicable
|term:eco[eco:inventoryTypes]
|`Open search`

|term:eco[eco:compilationTypes]
|`compilationOfExistingSourcesAndSamplingEvents`


|term:eco[eco:compilationSourceTypes]
|`museumSpecimens \| literature`
|===

==== Sampling protocol

Four protocol terms exist, however, only 1 term is currently required to publish a sampling Event dataset in GBIF: term:dwc[dwc:samplingProtocol]. This requirement is because the initial Darwin Core Event classification only included the one term. The Humboldt extension introduced an additional three terms to capture information about sampling protocol in a more structured manner:

* term:eco[eco:protocolNames] +
* term:eco[eco:protocolDescriptions] +
* term:eco[eco:protocolReferences]

****
[discrete]
==== *Updated recommended best practice for reporting sampling protocol*
* Report the name(s) of the sampling protocol with term:eco[eco:protocolNames]. +
* Capture details of the methods or protocols implemented using term:eco[eco:protocolDescriptions]. +
* Provide citation information for the protocol via term:eco[eco:protocolReferences]. +
* Retain term:dwc[dwc:samplingProtocol] as a verbatim field of term:eco[eco:protocolNames].
****

[caption=""]
.Survey Event protocol terms, their recommended usage (status), and example data entries.
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Required
|term:dwc[dwc:samplingProtocol]
|`Visual survey`

.3+|Recommended
|term:eco[eco:protocolNames]
|`Visual survey`

|term:eco[eco:protocolDescriptions]
|`For each site a total list of lichen species (lichenized fungi) was produced based on a careful examination of soil, wood, stone surfaces and bark of trees up to 2m at three time periods: October-November 2014, February-December 2015 and March and May 2016. Specimens that were not possible to identify with certainty in the field were sampled and subsequently identified in the laboratory. For each species the substrate, e.g. phorophyte (host) species was recorded. All records were registered in www.svampeatlas.dk, and the nomenclature used is in accordance with this database.`

|term:eco[eco:protocolReferences]
|`See Appendix B of Brunbjerg, A.K., Bruun, H.H., Brøndum, L. et al. A systematic survey of regional multi-taxon biodiversity: evaluating strategies and coverage. BMC Ecol 19, 43 (2019). https://doi.org/10.1186/s12898-019-0260-x \| https://doi.org/10.17504/protocols.io.kxygx3jwkg8j/v1`
|===

==== Absences

*Organismal <<absence, absences>>* are defined here as the lack of detection of organisms that are members of an explicitly stated as part of the target taxonomic scope. Absence information is critical to understanding species´ biogeography, modeling species' responses to climate- and human-induced environmental change, conservation planning and resource management, monitoring, restorations, eradications or reintroductions, or other aspects of biodiversity dynamics.

* If the dataset includes absence information for one or more occurrences (to be reported in the `occurrence` table as term:dwc[dwc:occurrenceStatus] = `absent`), then term:eco[eco:isAbsenceReported] = `true`. +
* A list of absent taxa can be provided using term:eco[eco:absentTaxa] at all relevant Event levels. Absences should only be reported for taxa within the stated taxonomic and/or organismal scope of a survey and should use scientific nomenclature. Absence cannot be asserted for bycatch.

See the section 'link:#reporting-absences[Reporting absences]' for details on reporting absence information at the Occurrence level.

==== Abundance

<<abundance, *Abundance*>> is quantitative measure of the same taxonomic designation in a particular area at a specific time. Abundance data are a key indicator of ecological health. They are necessary for evaluating ecological patterns and dynamics, managing invasive species, informing effective habitat and ecosystem management, and for practical tasks such as quantifying existing resource.

* If the dataset includes any abundance information, term:eco[eco:isAbundanceReported] = `true` for all appropriate Event levels. If there is an abundance cap, then term:eco[eco:isAbundanceCapReported] = `true` and the value of the cap should be reported in term:eco[eco:abundanceCap]. +
* If there is no abundance cap, then term:eco[eco:isAbundanceCapReported] = `false`.

See the section 'link:#abundance-information[Abundance information]' for details on reporting absence information at the Occurrence level.

[caption=""]
.Absence and abundance terms, their recommended usage (status), and example data entries.
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
.3+|Recommended
|term:eco[eco:isAbsenceReported]
|`true` or `false`

|term:eco[eco:isAbundanceReported]
|`true` or `false`

|term:eco[eco:isAbundanceCapReported]
|`true` or `false`

.2+|Share if available
|term:eco[eco:absentTaxa] |

|term:eco[eco:abundanceCap] |`5`
|===

==== Material samples

A <<materialSample, *material sample*>> (term:dwc[dwc:MaterialSample]) is a physical entity ´... that represents an entity of interest in whole or in part.´ Essentially, material samples are specimens collected during a survey Event. A material sample may consist of an entire organism, part of an organism, or a genetic sample, or even multiple organisms not necessarily of the same taxonomic designation.

If the dataset includes at least one specimen from which a material sample was taken:

* term:eco[eco:hasMaterialSamples] = `true` at the appropriate child Event level and at any relevant parent Event level, and +
* the type(s) of materials collected should be listed under term:eco[eco:materialSampleTypes] for each relevant Event level.

If the dataset or sampling Event does _not_ include material samples:

* term:eco[eco:hasMaterialSamples] = `false` at all appropriate sampling Event levels.

==== Vouchers

A <<voucher, *voucher*>> is a physical specimen or material sample collected and accessioned into a museum collection in support of a specific project or survey.

If the dataset has vouchers:

* term:eco[eco:hasVouchers] = `true` at the appropriate child Event level and at any relevant parent Event level, and +
* a list of institutions housing them should be shared in term:eco[eco:voucherInstitutions] for each relevant Event level.

If the dataset or sampling event does _not_ include vouchers:

* term:eco[eco:hasVouchers] = `false` at all appropriate sampling Event levels.

==== Sensitive data: data generalization & information withheld

Although the general recommendation is to share all biodiversity data available at its highest spatio-temporal resolution, situations exist where it is necessary to generalize data prior to sharing a dataset publicly or even withhold information completely. Two terms are available to communicate if data are generalized or withheld from the data: term:dwc[dwc:dataGeneralizations] and term:dwc[dwc:informationWithheld]. While it is the responsibility of the publisher to protect sensitive species occurrence data, it is also the data publisher´s responsibility to clearly communicate any relevant actions taken and to indicate if the full data are available upon request.

How you generalize sensitive data (e.g. restrict the resolution of the data) depends on the species´ category of sensitivity. Where there is low risk of adverse outcomes, unrestricted publication of sensitive species data remains appropriate. See the published guide https://doi.org/10.15468/doc-5jp4-5g10[Current Best Practices for Generalizing Sensitive Species Occurrence Data^] or guidance on when and how to generalize or withhold information sensitive biodiversity data <<Chapman2020>>. The guide is also available in https://docs.gbif.org/sensitive-species-best-practices/master/fr/[French^] and https://docs.gbif.org/sensitive-species-best-practices/master/es/[Spanish^].

*Reporting data generalizations*

When generalizing data you should try not to reduce the value of the data for analysis, and a clear summary of the data generalization process should be reported at the appropriate Event level(s) using term:dwc[dwc:dataGeneralizations].

For example, if the spatial resolution of locality data for an event is reduced to the nearest half degree, then term:dwc[dwc:dataGeneralizations] = `Coordinates generalized from original GPS coordinates to the nearest half degree grid cell`  for each event to which this treatment was applied. If the location information was generalized for every sampling event site in a nested hierarchy, then at the parent Event level term:dwc[dwc:dataGeneralizations] = `Coordinates for each event site generalized from original GPS coordinates to the nearest half degree grid cell`.

*Reporting information withheld*

If specific data are not reported with the dataset, a clarifying statement should be provided at the appropriate Event level using term:dwc[dwc:informationWithheld].

For example, if sensitive species data are purposefully excluded from the published data, term:dwc[dwc:informationWithheld] should include a statement along the lines of `Sensitive species occurrence information not reported`.

==== Least specific target category quantity inclusive

The term term:eco[eco:isLeastSpecificTargetCategoryQuantityInclusive] indicates if the total number of organisms detected for a term:dwc[dwc:Taxon] (including all its subgroups) is shown in one record using the dwc:organismQuantity value. This true/false (Boolean) term helps data users know if the numbers given with term:dwc and term:dwc include all organisms of that dwc:Taxon.

* For term:eco[eco:isLeastSpecificTargetCategoryQuantityInclusive] to be `true`, the values shared in term:dwc[dwc:organismQuantity] and term:dwc[dwc:organismQuantityType] reported in a single Occurrence record are inclusive of all organisms of the dwc:Taxon detected during the survey Event.

* For term:eco[eco:isLeastSpecificTargetCategoryQuantityInclusive] to be `false`, the values shared in term:dwc[dwc:organismQuantity] and term:dwc[dwc:organismQuantityType] reported in a single occurrence record are NOT inclusive of all organisms of the dwc:Taxon detected during the survey Event. This means that to find the total number of organisms detected for a given dwc:Taxon, you need to add up the dwc:organismQuantity values from several occurrence records within the Event.

See https://eco.tdwg.org/inclusive/[Guidelines for eco:isLeastSpecificTargetCategoryQuantityInclusive] <<tdwg2024a>> for more information.

==== Verbatim fields

Two verbatim fields are available to provide additional information about an Event. 

* *Field notes:* Field notes can be copied, transcribed verbatim, or linked into term:dwc[dwc:fieldNotes]. +
* *Event remarks:* Additional comments about a particular Event that don't fit in any other term can be shared using term:dwc[dwc:eventRemarks].

Both fields can be applied to any Event at any level.

[caption=""]
.Other survey protocol information and verbatim protocol terms, their recommended usage (status), and example data entries.
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
.3+|Recommended
|term:eco[eco:hasMaterialSamples]
|`true` or `false`

|term:eco[eco:hasVouchers]
|`true` or `false`

|term:eco[eco:isLeastSpecificTargetCategoryQuantityInclusive]
|`true` or `false`

.6+|Share if available
|term:eco[eco:materialSampleTypes]
|`wholeOrganism`, `blood`

|term:eco[eco:voucherInstitutions]
|`AMNH \| KUNHM`

|term:dwc[dwc:dataGeneralizations]
|`Coordinates generalized from original GPS coordinates to the nearest half degree grid cell`, `Coordinates for each event site generalized from original GPS coordinates to the nearest half degree grid cell`

|term:dwc[dwc:informationWithheld]
|`Sensitive species occurrence information not reported`

|term:dwc[dwc:fieldNotes]
|`Notes available in the Grinnell-Miller Library`

|term:dwc[dwc:eventRemarks]
|
|===

=== Scope and completeness

*Survey <<scope, scope>>* relates the organisms targeted (or not targeted) during a survey. Structured reporting of explicitly stated survey scopes is necessary for evaluating and reporting completeness and is critical to understanding if the data can be used to assert absences (non-detections) of taxa. 

*Completeness* indicates the thoroughness of a survey relative to the stated scope. Structured reporting of explicitly stated survey scopes and completeness is necessary for evaluating and reporting completeness and is critical to understanding if the data can be used to assert absences (non-detections) of taxa. Reported scope and completeness information facilitates the ability of downstream data users to interpret species populations, areas of occupancy, infer species absences, etc. 

The 'target' and 'excluded' scope terms (e.g., term:eco[eco:targetTaxonomicScope]) presented in this section are the only survey event terms designed to capture _intent_. That is, these terms capture the breadth of the information the biological survey _intended_ to capture. All other terms should be used to report the actuality of the survey (e.g., what protocol was in practice implemented, and what information was actually collected).

****
[discrete]
==== Implementing scope terms
* Scope terms can be applied at any Event level. +
* Recommended best practice is to populate scope terms for the highest level Event to which they apply, and all of its child Events. This information should be reported ONLY at the Event levels for which the information is explicitly stated (information should not be inferred up or down an event hierarchy). +
* Scope terms of an Event MUST be populated whenever the scope was in effect to be able to infer absence of detection within that Event whenever the Occurrences linked to that Event do not explicitly state zero counts or when there are no Occurrence records for a given taxon that fell within the taxonomic scope (see Section 3.2.4 Principle of inference in https://eco.tdwg.org/hierarchy/#324-principle-of-inference[Properties of hierarchical events in the Humboldt Extension for Ecological Inventories^]). +
* Do NOT retrospectively infer scope terms.
****

==== Verbatim scope

The full verbatim scope explicitly identifying the full suite of stated parameters defining the breadth of a sampling Event should be reported using term:eco[eco:verbatimTargetScope]. term:eco[eco:verbatimTargetScope] is particularly useful for capturing scope conditions not covered by existing https://eco.tdwg.org/terms/#taxonomic-scope[taxonomic^] or https://eco.tdwg.org/terms/#organismal-scope[organismal^] scope terms.

[caption=""]
.General scope terms, their recommended usage (status), and example data entries.
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Recommended
|term:eco[eco:verbatimTargetScope]
|`Adult flying insects`
|===

==== Taxonomic scope

Reporting taxonomic scope enables reliable, quantitative, including statistical interpretation of survey and monitoring data. Knowledge of taxonomic scope is essential to interpret local non-detection as local absences. The *taxonomic scope*, stated either as targeted or intentionally excluded taxa, should be reported using term:eco[eco:targetTaxonomicScope] and term:eco[eco:excludedTaxonomicScope].

If every organism in the stated terms:eco[eco:targetTaxonomicScope] that was observed during an Event was reported, then term:eco[eco:isTaxonomicScopeFullyReported] = `true`; if not, term:eco[eco:isTaxonomicScopeFullyReported] = `false`.

*Knowledge about taxonomic completeness* allows data users to determine how comprehensively an area was sampled. 

* If taxonomic completeness is reported, then term:eco[eco:taxonCompletenessReported] = `reportedComplete` or `reportedIncomplete` as appropriate and the method used to assess completeness reported in term:eco[eco:taxonCompletenessProtocols]. +
* If taxonomic completeness is not reported: term:eco[eco:taxonCompletenessReported] = `notReported`.

If a specific person(s) or organization(s) are recorded as making the taxonomic identifications relevant to the stated survey scope(s), they should be acknowledged using the term:dwc[dwc:identifiedBy]. A list of names can be be shared with values separated by a `|`. Note that it is not currently possible to share a list of unique identifiers such as ORCID´s at the Event level.


[caption=""]
.Taxonomic scope terms, their recommended usage (status), and example data entries.
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
.2+|Recommended
|term:eco[eco:targetTaxonomicScope]
|`Arthropods`

|term:eco[eco:excludedTaxonomicScope]
|`Aves`

.4+|Share if available
|term:eco[eco:isTaxonomicScopeFullyReported]
|`true` or `false`

|term:eco[eco:taxonCompletenessReported]
|`reportedComplete`, `reportedIncomplete`, or `notReported`

|term:eco[eco:taxonCompletenessProtocols]
|`Based on sampling effort`

|term:dwc[dwc:identifiedBy]
|
|===

==== Organismal scopes

As with taxonomic scope, providing information about other organismal scopes when relevant enables reliable, quantitative interpretation of survey and monitoring data and can be essential to interpreting local non-detection as local absences. Three categories of terms are available with which to report an explicitly stated target or excluded *organismal scope*, and state whether or not all target organisms observed were reported. Any additional organismal scopes should be reported using term:eco[eco:verbatimTargetScope].

*Life stage*

<<lifeStage, Life stage>> refers to a distint phase in an organism's life cycle targeted for or excluded from a survey (see term:dwc[dwc:lifeStage]). Life stage may represent a spcific developmental, growth, and/or reproductive changes in an organism's life.

* If the survey targeted or excluded specific organismal life stages, the information should be reported in term:eco[eco:targetLifeStageScope] and term:eco[eco:excludedLifeStageScope]. +
* If every organism that was included within the life stage scope and was detected during the survey was reported, then term:eco[eco:isLifeStageScopeFullyReported] = `true`. Otherwise, term:eco[eco:isLifeStageScopeFullyReported] = `false`.

A corresponding term:dwc[dwc:lifeStage] term is available in the Occurrence extension. This term should be used to report life stage information for organism Occurrences in the `occurrence` table.


*Growth form*

<<growthForm, Growth form>> refers to the physical characters or habits of an organism, or group of organisms, in a given environment. It describes their specific shape, structure, and/or pattern of construction.

* If the survey targeted or excluded specific organismal growth forms, the information should be reported in term:eco[eco:targetGrowthFormScope] and term:eco[eco:excludedGrowthFormScope] .  
* If every organism in the stated growthform scope that was observed during the survey was reported, then term:eco[eco:isGrowthFormScopeFullyReported] = `true`; if not, term:eco[eco:isGrowthFormScopeFullyReported] = `false`. +

*Degree of establishment*

<<degreeOfEstablishment, Degree of establishment>> refers to ´the degree to which an organism survives, reproduces, and expands its range at the given place and time´ (see term:dwc[dwc:degreeOfEstablishment]).

* If the survey targeted or excluded specific organismal degree of establishment, the information should be reported in term:eco[eco:targetDegreeOfEstablishmentScope] and term:eco[eco:excludedDegreeOfEstablishmentScope]. +
* If every organism that was included within the degree of establishment, and was detected during the survey, was reported, then term:eco[eco:isDegreeOfEstablishmentScopeFullyReported] = `true`; otherwise, term:eco[eco:isDegreeOfEstablishmentScopeFullyReported] = `false`.

A corresponding term:dwc[dwc:degreeOfEstablishment] term is available in the Occurrence extension. This term can be used to report the degree to which information about establishment is available for organism Occurrences in the `occurrence` table.

[caption=""]
.Organismal scope terms, their recommended usage (status), and example data entries.
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
.8+|Share if available
|term:eco[eco:targetLifeStageScope]
|`larva`

|term:eco[eco:excludedLifeStageScope]
|`adult \| juvenile`

|term:eco[eco:isLifeStageScopeFullyReported]
|`true` or `false`

|term:eco[eco:targetDegreeOfEstablishmentScope]
|`native`

|term:eco[eco:excludedDegreeOfEstablishmentScope]
|`invasive`

|term:eco[eco:isDegreeOfEstablishmentScopeFullyReported]
|`true` or `false`

|term:eco[eco:targetGrowthFormScope]
|`tree`

|term:eco[eco:excludedGrowthFormScope]
|`shrub`

|term:eco[eco:isGrowthFormScopeFullyReported]
|`true` or `false`
|===

==== Bycatch

<<bycatch, *Bycatch*>> are organisms detected during a survey that were not explicitly targeted in the scope of a study. Bycatch, or a lack thereof, in a dataset can be reported at the taxonomic and organismal levels.

If *_taxonomic_* bycatch are reported: 

* Populate term:eco[eco:hasNonTargetTaxa] as `true` at all relevant Event levels. +
* If ALL *_taxonomic_* bycatch (term:eco[eco:hasNonTargetTaxa] = `true`) captured/observed during an Event are reported in the dataset: 
** term:eco[eco:areNonTargetTaxaFullyReported] = `true` +
** and a list of taxonomic bycatch should be shared in term:eco[eco:nonTargetTaxa] using scientific nomenclature. Entries in a list should be separated by a `\|`.

If *_organismal_* bycatch are reported:

* term:eco[eco:hasNonTargetOrganisms] = `true` at all relevant Event levels.

If the dataset does NOT include taxonomic or organismal bycatch:

* term:eco[eco:hasNonTargetTaxa] = `false` for all relevant Events and
* term:eco[eco:hasNonTargetOrganisms] = `false` for all relevant Events.

[caption=""]
.Bycatch terms, their recommended usage (status), and example data entries.

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
.4+|Share if available
|term:eco[eco:hasNonTargetTaxa]
|`true` or `false`

|term:eco[eco:areNonTargetTaxaFullyReported]
|`true` or `false`

|term:eco[eco:nonTargetTaxa]
|`Parabuteo unicinctus \| Geranoaetus melanoleucus; Cetoniinae \| Aclopinae \| Cyclocephala modesta`

|term:eco[eco:hasNonTargetOrganisms]
|`true` or `false`
|===

==== Habitat scope

If the survey includes an explicitly stated targeted or excluded *habitat scope* these can be reported in term:eco[eco:targetHabitatScope] and term:eco[eco:excludedHabitatScope].

The actual habitat observed at a survey site during an Event should be reported in term:dwc[dwc:habitat].

[caption=""]
.Habitat scope terms, their recommended usage (status), and example data entries.
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
.2+|Share if available
|term:eco[eco:targetHabitatScope]
|`deciduous forest`

|term:eco[eco:excludedHabitatScope]
|`urban`
|===

=== Sampling Effort

<<samplingEffort, *Sampling effort*>> communicates information about the likelihood that a type of organism will be detected: greater effort generally leads to equal higher probability of detection. Clear reporting of sampling effort is necessary for interpretation of measures of completeness and calculation of abundance (relative or absolute) or biomass, and is critical in assessing the ability to compare information and aggregate data across studies. 

The DwC Event term term:dwc[dwc:samplingEffort] is currently a recommended field when publishing Event datasets to GBIF; however, this term captures sampling effort in an unstructured way. The Humboldt extension includes 5 terms to more explicitly describe information about aspects of sampling effort. The updated **_recommended best practice_**  is to report sampling effort information as structured data using the Humboldt Extension terms. Through these terms, data providers may explicitly provide the following information: 

* *Is sampling effort reported?:* Indicate if sampling effort is reported (`true` or `false`) in term:eco[eco:isSamplingEffortReported]. +
* *Sampling effort protocol:* term:eco[eco:samplingEffortProtocol] should contain a textual description of the sampling effort protocol (e.g., number and arrangement of people or sensors deployed, whether or not sensors were mobile or stationary, how frequently observation, measurements, or samples were taken) and/or provide a link to the protocol used. +
* *Sampling effort:*  report sampling effort (the total amount of time of the sampling Event) value and units (e.g., 4 trap nights) using the paired terms term:eco[eco:samplingEffortValue] and term:eco[eco:samplingEffortUnit]. +
* *Sampling performed by:* term:eco[eco:samplingPerformedBy] should be used to credit the people involved in the sampling eventSampling effort terms, their recommendation usage, and example data entries. Best practice is to use a unique identifier (e.g., ORCID) if available.
** NOTE: Because term:eco[eco:samplingPerformedBy] has an <<IRI, IRI>> (internationalized resource identifier) equivalent only a single ORCID can be provided (the term cannot support a list). If more than one ORCID needs to be shared, a list of ORCID´s (using the pipe separator between values) can be supplied using the term term:dwc[dwc:recordedByID] used BUT it must be applied to each relevant Occurrence and located on the `occurrence` table.


[NOTE]
.*Updated recommended best practice*
====
Capture sampling effort information as structured data using the following Humboldt extension terms:

* term:eco[eco:isSamplingEffortReported]
* term:eco[eco:samplingEffortValue] and term:eco[eco:samplingEffortUnit]
* term:eco[eco:samplingEffortProtocol]
* term:eco[eco:samplingPerformedBy]
====

[caption=""]
.Sampling effort terms, their recommended usage (status), and example data entries.
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
.6+|Recommended
|term:eco[eco:isSamplingEffortReported]
|`true` or `false`

|term:eco[eco:samplingEffortProtocol]
|`40 box traps deployed in the afternoon even spacings along 4 parallel 100m transects placed 50m apart and visited after sunrise the next day`

|term:eco[eco:samplingEffortValue]
|`40`

|term:eco[eco:samplingEffortValue]
|`trap nights`

|term:dwc[dwc:samplingEffort]
|`40 trap nights`

|term:eco[eco:samplingPerformedBy]
|`A. Townsend Peterson`
|===

<<<
