[[survey-event-data:-capturing-the-context-of-biological-surveys]]
== Survey event data: capturing the context of biological surveys

The following sections will guide you through the process of mapping
Event level information specifically related to survey structure,
location, protocols, scopes, and efforts.

[IMPORTANT]
.*Survey level information in DWC-A files*
====
Survey event data should be
saved to the DwC-A event table. This includes DwC Event terms (any term
preceded by _`dwc'_, e.g.,
http://rs.tdwg.org/dwc/terms/eventID[_dwc:eventID_]) and Humboldt
extension terms (any term preceded by _`eco'_, e.g.,
http://rs.tdwg.org/eco/terms/protocolNames[_eco:protocolNames_]).

  - A
comprehensive list of Darwin Core terms that can be applied at the event
level can be found on the Darwin Core Event page in the GBIF Registry of
Schemas (https://rs.gbif.org/core/dwc_event_2024-02-19.xml). 
  - The full
suite of Humboldt Extension terms is available on the Humboldt
Ecological Inventories page in the GBIF Registry of Schemas
(https://rs.gbif.org/extension/eco/Humboldt_2024-04-16.xml) and in the
Humboldt Extension Quick Reference Guide (https://eco.tdwg.org/terms/).

Fields for which there is no data to share at any hierarchical level can
be left blank or simply not included in the Event table. Populating
terms across event levels (e.g., from parent event to child event) 

Each event level can have its own set of attributes and measurements, which
can be captured using the Humboldt and/or other Extension(s) and be
unambiguously linked to the corresponding level through the appropriate
__dwc:eventID__s. 

A parent Event should not be populated by deriving or
summarizing information from child Events; rather, fields SHOULD be
populated explicitly with information directly appropriate to the nature
and level of the event itself (see Section _3.2.3 Principle of
non-derivation_ in the `https://eco.tdwg.org/hierarchy/[Properties of
hierarchical events in the Humboldt Extension for Ecological
Inventories]'). 

A child event SHOULD NOT implicitly inherit the value of
any property of any of its parent Event(s). If a value is in common
between an Event and its parent, the value should be included explicitly
in both Event records. 

Refer to https://eco.tdwg.org/hierarchy/[Properties of hierarchical events in the
Humboldt Extension for Ecological Inventories^] for guidance in
populating Humboldt extension terms across event levels.
====

=== Survey design

Survey sampling design specifies survey strategy and how the stations or
transects are laid out. Historically, only 2 terms were available to
explicitly structure and relate different levels of survey design in a
dataset: http://rs.tdwg.org/dwc/terms/eventID[_dwc:eventID_] and
http://rs.tdwg.org/dwc/terms/parentEventID[_dwc:parentEventID_]. One
additional Darwin Core event term,
http://rs.tdwg.org/dwc/terms/fieldNumber[_dwc:fieldNumber_], provided a
means by which to relate a sampling event with a dataset- or project-
specific field number. Humboldt extension provides an additional 2
terms—http://rs.tdwg.org/eco/terms/siteCount[_eco:siteCount_] and
http://rs.tdwg.org/eco/terms/siteNestingDescription[_eco:siteNestingDescription_]—
to better support complex or nested dataset.

[NOTE]
.*Event data in GBIF*
====
- Any dataset to be published using the DwC event core
must have at least 1 event record with a unique
http://rs.tdwg.org/dwc/terms/eventID[_dwc:eventID_].
- Each http://rs.tdwg.org/dwc/terms/eventID[_dwc:eventID_] in a dataset must be
unique within the dataset. Use of a persistent globally unique
identifier (GUID) is recommended (this can be the original field
number). A unique http://rs.tdwg.org/dwc/terms/eventID[_dwc:eventID_]
should be reused between datasets where appropriate (for example, where
data collected during the same sampling event are published as multiple
datasets). See
https://assets.ctfassets.net/uo17ejk9rkwj/8aIUAbLo0oycyMiM2IKUS/363edf7ab4558460cfe1ef140567450f/persistent_identifiers_guide_en_v1.pdf[A
Beginner’s Guide to Persistent Identifiers] for guidance in creating
persistent identifiers. 
- An event is not required to have associated
organism occurrence data. If organism occurrence or non-detection data
are available, they are connected via the
http://rs.tdwg.org/dwc/terms/eventID[_dwc:eventID_] to the event and the
https://rs.gbif.org/core/dwc_occurrence_2024-02-23.xml[Occurrence
extension]. 
- DwC event core extensions, including
https://rs.gbif.org/core/dwc_occurrence_2024-02-23.xml[occurrence],
https://rs.gbif.org/extension/obis/extended_measurement_or_fact_2023-08-28.xml[extended
measurements or facts], and
https://rs.gbif.org/extension/gbif/1.0/releve_2016-05-10.xml[Relevé]
extensions, can be applied to any event level via the appropriate
http://rs.tdwg.org/dwc/terms/eventID[_dwc:eventID_].
====

*Non-nested datasets*

* Each event in a non-nested dataset must be assigned a unique
http://rs.tdwg.org/dwc/terms/eventID[_dwc:eventID_]. +
* Non-nested datasets will not have a
http://rs.tdwg.org/dwc/terms/parentEventID[_dwc:parentEventID_] and
http://rs.tdwg.org/eco/terms/siteNestingDescription[_eco:siteNestingDescription_]
does not need to be populated.

*Nested datasets*

Nested hierarchies are established by relating a child event to a parent
event through the child Event’s
http://rs.tdwg.org/dwc/terms/parentEventID[_dwc:parentEventID_]. As
such, these more complex datasets require use of both
http://rs.tdwg.org/dwc/terms/eventID[_dwc:eventID_] and
http://rs.tdwg.org/dwc/terms/parentEventID[_dwc:parentEventID_].

* Each event in a nested dataset must have a unique
http://rs.tdwg.org/dwc/terms/eventID[_dwc:eventID_]. +
* Each parent event must have its own
http://rs.tdwg.org/dwc/terms/parentEventID[_dwc:parentEventID_].

In addition to event and parent event identifiers:

* *Site count and site nesting description:* Nested datasets should, at
the parent event level, include the total number of sites sampled in
http://rs.tdwg.org/eco/terms/siteCount[_eco:siteCount_] and provide a
textual description of the survey design or site sampling structure
using
http://rs.tdwg.org/eco/terms/siteNestingDescription[_eco:siteNestingDescription_]. +
* *Field number:* If the survey data include a field number for each
specific event, this should be shared using
http://rs.tdwg.org/dwc/terms/fieldNumber[_dwc:fieldNumber_].

[caption=]
.Event hierarchy terms, their recommended usage (status), and example data entries.
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Required |term:dwc[dwc:eventID]
|survey2022_a-2

|Required for nested datasets
|term:dwc[dwc:parentEventID]
|survey2022

|.2 Recommended |term:eco[eco:siteCount]
|75

|
|term:eco[eco:siteNestingDescription]
|25 survey sites each with 3 1m2 quadrats

|Share if available
|term:dwc[dwc:fieldNumber] 
|RV Sol 87-03-08
|===

[cols="1,2,3", options="header"]
|===
| Header 1 | Header 2 | Header 3

| Row 1, Col 1 | Row 1, Col 2 | Row 1, Col 3
| Row 2, Col 1 | Row 2, Col 2 | Row 2, Col 3
| Row 3, Col 1, colspan=2 | Row 3, Col 2 | Row 3, Col 3
| Row 5, Col 1 | Row 4, Col 2 | Row 4, Col 3
| Row 5, Col 1 | Row 5, Col 2 | Row 5, Col 3
|===

=== Survey site

An event *_site_* is the location at which observations are made or
samples and/or measurements are taken. Sharing thorough information
about a sampling event site, including description, locality, and
vegetative cover provides critical context to potential data users about
conditions in which survey was conducted. Information about the location
of each survey site including geographic coordinates with geodetic
datum, site description (locality name, habitat type, microhabitat), and
environmental data (e.g., physical parameters, vegetarian, water
quality) should be populated at every event level.

NOTE: The Darwin Core site terms listed in this section are not
comprehensive. Explore all Darwin Core Location class terms
(http://purl.org/dc/terms/Location) and the Humboldt Extension site
terms (https://eco.tdwg.org/terms/#site).

==== Site description

Context about a survey event site can be provided through a multitude of
terms that shared for every event level that the information is
available, including:

* *Site names:* report individual sampling event site names using
http://rs.tdwg.org/eco/terms/verbatimSiteNames[_eco:verbatimSiteNames_].
A concatenated list of site names can be provided at higher event
levels. +
* *Habitat:* reported habitat at a sampling event site should be
recorded in http://rs.tdwg.org/dwc/terms/habitat[_dwc:habitat_]. A
concatenated list of habitats can be provided at higher event levels. +
* *Weather:* reported weather at a sampling event site should be
recorded in
http://rs.tdwg.org/eco/terms/reportedWeather[_eco:reportedWeather_]. +
* *Extreme conditions:* reported extreme conditions at a sampling event
site at the time of the survey event should be recorded in
http://rs.tdwg.org/eco/terms/reportedExtremeConditions[_eco:reportedExtremeConditions_]. +
* *Verbatim site description:* verbatim comments (e.g., the original
textual description) about a site or sites should be copied in
http://rs.tdwg.org/eco/terms/verbatimSiteDescriptions[_eco:verbatimSiteDescriptions_].

These terms should be populated at any hierarchical event level that is
appropriate.

General event site terms, their recommended usage (status), and example
data entries..

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Share if available
|_http://rs.tdwg.org/eco/terms/verbatimSiteNames[eco:verbatimSiteNames]_
|`Trap_18'

| |_http://rs.tdwg.org/dwc/terms/habitat[dwc:habitat]_ |`Ephemeral
wetland'

| |http://rs.tdwg.org/eco/terms/reportedWeather[_eco:reportedWeather_]
|\{``minimumTemperatureInDegreesFahrenheit'': 18,
``maximumTemperatureInDegreesFahrenheit'': 32}

|
|_http://rs.tdwg.org/eco/terms/reportedExtremeConditions[eco:reportedExtremeConditions]_
|`Site flooded'

|
|_http://rs.tdwg.org/eco/terms/verbatimSiteDescriptions[eco:verbatimSiteDescriptions]_
|`Coastal sand dunes at dry oak forest edge. Vegetation: Ammophila
arenaria, Betula pendula, Leymus arenarius, Pinus sylvestris'
|===

==== Site locality

The geographic location and extent of each survey event site should be
provided. Historically, 5 terms were strongly recommended for event
datasets in GBIF:

* *Location ID:* a unique identifier for each sampling event site should
be shared in
*http://rs.tdwg.org/dwc/terms/locationID[dwc:locationID*]. +
* *Country code:* the two letter code for the country in which the
survey takes place should be provided in
*http://rs.tdwg.org/dwc/terms/countryCode[dwc:countryCode*]. +
* *Latitude-Longitude:* The decimal latitude and longitude and geodetic
datum location of the Event site should be provided in
http://rs.tdwg.org/dwc/terms/decimalLatitude[_dwc:decimalLatitude_],
http://rs.tdwg.org/dwc/terms/decimalLongitude[_dwc:decimalLongitude_],
and http://rs.tdwg.org/dwc/terms/geodeticDatum[_dwc:geodeticDatum_].
** If geographic coordinates are not in decimal latitude and decimal
longitude format, populate
http://rs.tdwg.org/dwc/terms/verbatimLatitude[_dwc:verbatimLatitude_],
http://rs.tdwg.org/dwc/terms/verbatimLongitude[_dwc:verbatimLongitude_],
and
http://rs.tdwg.org/dwc/terms/verbatimCoordinateSystem[_dwc:verbatimCoordinateSystem_]
instead.

The Humboldt extension includes additional terms that provide greater
contextual information about the geospatial scope of a sampling event or
series of events.

==== Survey site area

It is highly recommended to report additional information on the
targeted area and the area actually sampled to understand the geospatial
scope of the survey. Two sets of paired terms are available to report
the area of an event or survey site: _geospatial scope_ terms and _total
area sampled_ terms. *_Geospatial scope_* terms
(http://rs.tdwg.org/eco/terms/geospatialScopeAreaValue[_eco:geospatialScopeAreaValue_]
and
http://rs.tdwg.org/eco/terms/geospatialScopeAreaUnit[_eco:geospatialScopeAreaUnit_])
define the geospatial scope or extent of a survey or sampling event.
*_Total area sampled_* terms
(http://rs.tdwg.org/eco/terms/totalAreaSampledValue[_eco:totalAreaSampledValue_]
and
http://rs.tdwg.org/eco/terms/totalAreaSampledUnit[_eco:totalAreaSampledUnit_])
report the total area sampled during an event.

* For *non-nested event datasets*,
http://rs.tdwg.org/eco/terms/geospatialScopeAreaValue[_eco:geospatialScopeAreaValue_]
and
http://rs.tdwg.org/eco/terms/geospatialScopeAreaUnit[_eco:geospatialScopeAreaUnit_],
and
http://rs.tdwg.org/eco/terms/totalAreaSampledValue[_eco:totalAreaSampledValue_]
and
http://rs.tdwg.org/eco/terms/totalAreaSampledUnit[_eco:totalAreaSampledUnit_]
may contain the same values. +
* In *nested datasets*,
http://rs.tdwg.org/eco/terms/geospatialScopeAreaValue[_eco:geospatialScopeAreaValue_]
and
http://rs.tdwg.org/eco/terms/geospatialScopeAreaUnit[_eco:geospatialScopeAreaUnit_]
should be used to report the full study extent at the parent event level
(the total area surveyed in a series of survey Events) and
http://rs.tdwg.org/eco/terms/totalAreaSampledValue[_eco:totalAreaSampledValue_]
and
http://rs.tdwg.org/eco/terms/totalAreaSampledUnit[_eco:totalAreaSampledUnit_]
should be used to relate the area of child event sites (e.g., individual
survey sites). Geospatial scope value(s) should always be greater than
or equal to that of total area sampled.

For example, consider the
https://www.gbif.org/dataset/cd4eb3ec-0a18-42b4-bda4-155716ddd7b1[Biowide
project] which surveyed 130 40x40m plots across Denmark. Here, the
project-level parent event would report the full geographic extent of
Denmark:
http://rs.tdwg.org/eco/terms/geospatialScopeAreaValue[_eco:geospatialScopeAreaValue_]
= `42934' and
http://rs.tdwg.org/eco/terms/geospatialScopeAreaUnit[_eco:geospatialScopeAreaUnit_]
= `km2'. The associated 130 child events representing each individual
survey site would then report the area of the site as
http://rs.tdwg.org/eco/terms/totalAreaSampledValue[_eco:totalAreaSampledValue_]
= `40' and
http://rs.tdwg.org/eco/terms/totalAreaSampledUnit[_eco:totalAreaSampledUnit_]
= `m2'.

*_If the sampled unit is not an area_* (such as a filtered volume of
water in a zooplankton haul),
http://rs.tdwg.org/dwc/terms/sampleSizeValue[_dwc:sampleSizeValue_] and
http://rs.tdwg.org/dwc/terms/sampleSizeUnit[_dwc:sampleSizeUnit_] should
be used in place of
http://rs.tdwg.org/eco/terms/totalAreaSampledValue[_eco:totalAreaSampledValue_]
and
http://rs.tdwg.org/eco/terms/totalAreaSampledUnit[_eco:totalAreaSampledUnit_].

==== Additional survey site information

* *Survey site geometry:* If available, the geometry of a survey site
area should be shared using
http://rs.tdwg.org/dwc/terms/footprintWKT[_dwc:footprintWKT_] and
http://rs.tdwg.org/dwc/terms/footprintSRS[_dwc:footprintSRS_]. +
* *Verbatim site location information:* A more general text description
of the site location, if available, can be shared using
http://rs.tdwg.org/dwc/terms/locality[_dwc:locality_].

Event site geographic locality and scope terms and their recommended
usage (status), namespace abbreviation, and example data entries.

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Recommended |*http://rs.tdwg.org/dwc/terms/locationID[dwc:locationID*]
|`Trap_138'

| |http://rs.tdwg.org/dwc/terms/countryCode[_dwc:countryCode_] |`SE'

| |http://rs.tdwg.org/dwc/terms/decimalLatitude[_dwc:decimalLatitude_]
|`59.3168'

| |http://rs.tdwg.org/dwc/terms/decimalLongitude[_dwc:decimalLongitude_]
|`18.0627'

| |http://rs.tdwg.org/dwc/terms/geodeticDatum[_dwc:geodeticDatum_]
|`WGS84'

|
|http://rs.tdwg.org/eco/terms/geospatialScopeAreaValue[_eco:geospatialScopeAreaValue_]
|`580000'

|
|http://rs.tdwg.org/eco/terms/geospatialScopeAreaUnit[_eco:geospatialScopeAreaUnit_]
|`km2'

|
|_http://rs.tdwg.org/eco/terms/totalAreaSampledValue[eco:totalAreaSampledValue]_
|`40'

|
|http://rs.tdwg.org/eco/terms/totalAreaSampledUnit[_eco:totalAreaSampledUnit_]
|`m2'

| |_http://rs.tdwg.org/dwc/terms/sampleSizeValue[dwc:sampleSizeValue]_
|`200'

| |_http://rs.tdwg.org/dwc/terms/sampleSizeUnit[dwc:sampleSizeUnit]_
|`m3'

|Share if available
|http://rs.tdwg.org/dwc/terms/footprintWKT[_dwc:footprintWKT_] |`POLYGON
((10 20, 11 20, 11 21, 10 21, 10 20))'

| |http://rs.tdwg.org/dwc/terms/footprintSRS[_dwc:footprintSRS_]
|`epsg:4326'

| |_http://rs.tdwg.org/dwc/terms/locality[dwc:locality]_ |`Agriculture
site, Kongskilde Friluftsgård, Zealand'
|===

==== Vegetation cover

Vegetation cover at a survey site can be reported in three ways:

* *Verbatim vegetation cover:* a verbatim description of vegetation
cover can be captured in
http://rs.tdwg.org/eco/terms/verbatimSiteDescriptions[_eco:verbatimSiteDescriptions_]. +
* *Percent vegetation cover:* simple percent vegetation cover can be
recorded as structured data using the
https://rs.gbif.org/extension/obis/extended_measurement_or_fact_2023-08-28.xml[extended
measurements or facts extension]. +
* *Vegetation plot survey:* vegetation plot survey information can be
reported using the
https://rs.gbif.org/extension/gbif/1.0/releve_2016-05-10.xml[Relevé
extension].

If vegetation cover is reported, then
http://rs.tdwg.org/eco/terms/isVegetationCoverReported[eco:_isVegetationCoverReported_]
= `true'; otherwise,
http://rs.tdwg.org/eco/terms/isVegetationCoverReported[eco:_isVegetationCoverReported_]
= `false'.

=== Survey date and time

Complete and accurate reporting of the temporal scope of a survey is
crucial to asserting event structure and providing key contextual
information about sampling conditions.

*Event date, time, and duration*

Each event should have a reported date or date range reported in
http://rs.tdwg.org/dwc/terms/eventDate[_dwc:eventDate_] regardless of
its hierarchical level. *Nested datasets* should, at the parent event
level, report a date range encompassing all survey dates.

If available, the time and duration of each event should be reported
using http://rs.tdwg.org/dwc/terms/eventTime[_dwc:eventTime_] and the
paired terms
http://rs.tdwg.org/eco/terms/eventDurationValue[_eco:eventDurationValue_]
and
http://rs.tdwg.org/eco/terms/eventDurationUnit[_eco:eventDurationUnit_].

Refer to GBIF’s technical documentation on
https://techdocs.gbif.org/en/data-processing/temporal-interpretation[Date
and time interpretation] for more guidance on reporting event dates and
times.

Event date and temporal scope terms, their recommended usage (status),
and example data entries.

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Required |http://rs.tdwg.org/dwc/terms/eventDate[_dwc:eventDate_]
|`2018-08-29'

|Recommended |_http://rs.tdwg.org/dwc/terms/eventTime[dwc:eventTime]_
|`08:00Z'

|
|http://rs.tdwg.org/eco/terms/eventDurationValue[_eco:eventDurationValue_]
|`1'

|
|http://rs.tdwg.org/eco/terms/eventDurationUnit[_eco:eventDurationUnit_]
|`hour'
|===

=== Methodology/sampling protocol \{#methodology/sampling-protocol}

*Sampling protocol* provides the details of how the sampling was
conducted. Clear communication of the sampling protocol implemented is
essential to ensuring the reliability, reproducibility, and reusability
of a dataset as detailed knowledge of survey methods facilitates data
integration and subsequent analysis.

*_Sampling protocol terms should be populated at every event level
possible as inheritance in either direction should not be assumed or
inferred between event levels._*

==== Event type

Biological survey event data can result from a wide variety of effort
types (e.g., Bioblitzes, inventories). The nature of the survey event
should be reported using
http://rs.tdwg.org/dwc/terms/eventType[_dwc:eventType_].

[width="100%",cols="<100%",options="header",]
|===
|Identifying event type
http://rs.tdwg.org/dwc/terms/eventType[_dwc:eventType_] should provide a
high level overview of sampling effort type but should not be so
specific as to overlap with sampling protocol. There is no single,
standardized vocabulary for
http://rs.tdwg.org/dwc/terms/eventType[_dwc:eventType_]. If your
organization or community has a controlled vocabulary, it is recommended
to apply terms from that. Otherwise, you can refer to the common event
types below for guidance. Project: Projects are structured initiatives
with explicitly stated objective or suite of objectives and with clear
targets, timelines, and deliverables. Projects typically are typically
linked to non-biological information identifying participating
organizations and people (agents), funding agencies, and other
high-level administrative information. Biological sampling may only be
one facet of a project’s scope. `Project' as a
http://rs.tdwg.org/dwc/terms/eventType[_dwc:eventType_] is typically
most appropriate only at the highest (parent) event level in a nested
dataset. Expedition: An expedition is an organized information gathering
venture that inherently includes multiple sampling events and event
types. Expeditions may include multiple taxonomic and/organismal scopes,
any number of documented sampling protocols, and varying degrees of
complexity in survey design. `Expedition' as a
http://rs.tdwg.org/dwc/terms/eventType[_dwc:eventType_] is typically
most appropriate at higher (parent) event levels in nested hierarchies.
Survey: A survey is a systematic effort to collect information about the
biological organisms in a specific area at a given time. Surveys
typically included at least one documented protocol and may or may not
have an explicitly defined taxonomic and/or organismal scope. `Survey'
is the most general event type term and can be applied as a
http://rs.tdwg.org/dwc/terms/eventType[_dwc:eventType_] at any event
level. Inventory: An inventory is a comprehensive survey of the taxa
present in a specific area over an explicit period of time. Inventories
typically have an explicit taxonomic and/or organismal scope and a
well-defined protocol. `Inventory' is typically most appropriate as a
http://rs.tdwg.org/dwc/terms/eventType[_dwc:eventType_] at lower (child)
event levels in nested hierarchies. Bioblitz: A bioblitz is a survey
event aimed at finding and identifying as many species as possible in a
specific area over a (typically) short, contiguous period of time.
Bioblitzes often include participants (agents) with a wide range of
backgrounds and levels of expertise in biodiversity sciences including
formal biologists as well as the broader, general public. `Bioblitz' as
a http://rs.tdwg.org/dwc/terms/eventType[_dwc:eventType_] is typically
most appropriate at lower (child) event levels in nested hierarchies.
Identification: An identification is the taxonomic identification of a
material sample or samples collected during an event. This could be an
identification by a professional taxonomist or through DNA analysis, but
it occurs at a time and place other than the survey site (e.g., a
laboratory).
|===

*`Inventory' event types*

* If http://rs.tdwg.org/dwc/terms/eventType[_dwc:eventType_] =
*`inventory'*, the type of search implemented (e.g., restricted search,
open search, opportunistic search, trap or sample, compilation) must be
reported in
http://rs.tdwg.org/eco/terms/inventoryTypes[_eco:inventoryTypes_]. +
* If _eco:inventoryTypes_ = ’*compilation’*, the compilation type should
be reported using
http://rs.tdwg.org/eco/terms/compilationTypes[_eco:compilationTypes_]
and data sources captured using
http://rs.tdwg.org/eco/terms/compilationSourceTypes[_eco:compilationSourceTypes_].
** A compilation is a summary inventory resulting from the combination
of multiple existing inventories (as described in Guralnick et
al. 2018). Compilations are aggregates of multiple studies, and may
combine surveys employing different protocols, processes, and observers,
often with variable reporting of the methods employed or other compiled
data sources and literature searches.

Event type terms, their recommended usage (status), and example data
entries..

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Recommended |http://rs.tdwg.org/dwc/terms/eventType[_dwc:eventType_]
|`Inventory'

|Recommended if applicable
|http://rs.tdwg.org/eco/terms/inventoryTypes[_eco:inventoryTypes_]
|`Open search'

| |http://rs.tdwg.org/eco/terms/compilationTypes[_eco:compilationTypes_]
|`compilationOfExistingSourcesAndSamplingEvents'

|
|http://rs.tdwg.org/eco/terms/compilationSourceTypes[_eco:compilationSourceTypes_]
|`museumSpecimens'
|===

==== Sampling protocol

Four protocol terms currently exist, however, only 1 term is required to
publish a sampling event dataset in GBIF:
http://rs.tdwg.org/dwc/terms/samplingProtocol[_dwc:samplingProtocol_].
This requirement is because the initial Darwin Core event classification
only included the one term. The Humboldt Extension introduced 3 terms to
capture information about sampling protocol in a more structured manner:

* http://rs.tdwg.org/eco/terms/protocolNames[_eco:protocolNames_] +
* http://rs.tdwg.org/eco/terms/protocolDescriptions[_eco:protocolDescriptions_] +
* http://rs.tdwg.org/eco/terms/protocolReferences[_eco:protocolReferences_]

[width="100%",cols="<100%",options="header",]
|===
|Updated recommended best practice Report the name(s) of the sampling
protocol with
http://rs.tdwg.org/eco/terms/protocolNames[_eco:protocolNames_]. Capture
details of the methods or protocols implemented using
http://rs.tdwg.org/eco/terms/protocolDescriptions[_eco:protocolDescriptions_].
Provide citation information for the protocol via
http://rs.tdwg.org/eco/terms/protocolReferences[_eco:protocolReferences_].
Retain
http://rs.tdwg.org/dwc/terms/samplingProtocol[_dwc:samplingProtocol_] as
a verbatim field of
http://rs.tdwg.org/eco/terms/protocolNames[_eco:protocolNames_].
|===

Survey event protocol terms, their recommended usage (status), and
example data entries.

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Required
|http://rs.tdwg.org/dwc/terms/samplingProtocol[_dwc:samplingProtocol_]
|`Visual survey'

|Recommended
|http://rs.tdwg.org/eco/terms/protocolNames[_eco:protocolNames_]
|`Visual survey'

|
|http://rs.tdwg.org/eco/terms/protocolDescriptions[_eco:protocolDescriptions_]
|`For each site a total list of lichen species (lichenized fungi) was
produced based on a careful examination of soil, wood, stone surfaces
and bark of trees up to 2 m at three time periods: October-November
2014, February-December 2015 and March and May 2016. Specimens that were
not possible to identify with certainty in the field were sampled and
subsequently identified in the laboratory. For each species the
substrate, e.g. phorophyte (host) species was recorded. All records were
registered in www.svampeatlas.dk, and the nomenclature used is in
accordance with this database.'

|
|http://rs.tdwg.org/eco/terms/protocolReferences[_eco:protocolReferences_]
|`See Appendix B of Brunbjerg, A.K., Bruun, H.H., Brøndum, L. et al. A
systematic survey of regional multi-taxon biodiversity: evaluating
strategies and coverage. BMC Ecol 19, 43 (2019).
https://doi.org/10.1186/s12898-019-0260-x'
|===

==== Absence and abundance

*Organismal absences* are defined here as the lack of detection of
organisms explicitly stated as part of the target taxonomic scope.
Absence information is critical to understanding species’ biogeography,
modeling species’ responses to climate- and human-induced environmental
change, and conservation planning and resource management.

* If the dataset includes absence information for one or more
occurrences (to be reported in the `occurrence' table as
_dwc:occurrenceStatus_ = `absent'), then
http://rs.tdwg.org/eco/terms/isAbsenceReported[_eco:isAbsenceReported_]
= `true'. +
* A list of absent taxa can be provided using
http://rs.tdwg.org/eco/terms/absentTaxa[_eco:absentTaxa_] at all
relevant levels. Absences should only be reported for taxa within the
stated taxonomic and/or organismal scope of a survey. Absence cannot be
asserted for bycatch.

See the section `link:#reporting-absences[Reporting absences]' for
details on reporting absence information at the occurrence level.

*Abundance* is the number of individuals of the same taxonomic
designation in a particular area at a specific time. Abundance data are
a key indicator of ecological health. They are necessary for conducting
biodiversity assessment, evaluating ecological health, managing invasive
species, and informing effective habitat and ecosystem management.

* If the dataset includes abundance information,
http://rs.tdwg.org/eco/terms/isAbundanceReported[_eco:isAbundanceReported_]
= `true' for all appropriate Event levels. If there is an abundance cap,
then
http://rs.tdwg.org/eco/terms/isAbundanceCapReported[eco:_isAbundanceCapReported_]
= `true' and the value of the cap should be reported in
http://rs.tdwg.org/eco/terms/abundanceCap[_eco:abundanceCap_]. +
* If there is no abundance cap, then
http://rs.tdwg.org/eco/terms/isAbundanceCapReported[eco:_isAbundanceCapReported_]
= `false'.

See the section `link:#abundance-information[Abundance information]' for
details on reporting absence information at the occurrence level.

Absence and abundance terms, their recommended usage (status), and
example data entries.

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Recommended
|http://rs.tdwg.org/eco/terms/isAbsenceReported[_eco:isAbsenceReported_]
|`true' or `false'

|
|http://rs.tdwg.org/eco/terms/isAbundanceReported[_eco:isAbundanceReported_]
|`true' or `false'

|
|http://rs.tdwg.org/eco/terms/isAbundanceCapReported[eco:_isAbundanceCapReported_]
|`true' or `false'

|Share if available
|http://rs.tdwg.org/eco/terms/absentTaxa[_eco:absentTaxa_] |

| |http://rs.tdwg.org/eco/terms/abundanceCap[_eco:abundanceCap_] |`5'
|===

==== Material samples

A *material sample* (http://rs.tdwg.org/dwc/terms/MaterialSample) is an
entity `… that represents an entity of interest in whole or in part.'
Essentially, material samples are specimens collected during the survey
event. They may consist of an entire organism, part of an organism, or a
genetic sample.

If the dataset includes at least one material sample:

* http://rs.tdwg.org/eco/terms/hasMaterialSamples[_eco:hasMaterialSamples_]
= `true' at the appropriate child event level and at any relevant parent
event level, and +
* the type(s) of materials collected should be listed under
http://rs.tdwg.org/eco/terms/materialSampleTypes[_eco:materialSampleTypes_]
for each relevant event level.

If the dataset or sampling event does _not_ include material samples:

* http://rs.tdwg.org/eco/terms/hasMaterialSamples[_eco:hasMaterialSamples_]
= `false' at all appropriate sampling event levels.

==== Vouchers

A *voucher* is a specimen or material sample collected and accessioned
into a museum collection in support of a specific project or survey
effort.

If the dataset has vouchers:

* http://rs.tdwg.org/eco/terms/hasVouchers[_eco:hasVouchers_] = `true'
at the appropriate child event level and at any relevant parent event
level, and +
* a list of institutions housing them should be shared in
http://rs.tdwg.org/eco/terms/voucherInstitutions[_eco:voucherInstitutions_]
for each relevant event level.

If the dataset or sampling event does _not_ include vouchers:

* http://rs.tdwg.org/eco/terms/hasVouchers[_eco:hasVouchers_] = `false'
at all appropriate sampling event levels.

==== Sensitive data: data generalization & information withheld \{#sensitive-data:-data-generalization-&-information-withheld}

Although the general recommendation is to share all biodiversity data
available at its highest spatio-temporal resolution, situations exist
where it is necessary to generalize data prior to sharing a dataset
publicly or even withhold information completely.

Two terms are available to communicate if data are generalized or
withheld from the data:
http://rs.tdwg.org/dwc/terms/dataGeneralizations[_dwc:dataGeneralizations_]
and
http://rs.tdwg.org/dwc/terms/informationWithheld[_dwc:informationWithheld_].
While it is the responsibility of the publisher to protect sensitive
species occurrence data, it is also the data publisher’s responsibility
to clearly communicate any relevant actions taken and to indicate if the
full data are available upon request..

How you generalize sensitive data (e.g. restrict the resolution of the
data) depends on the species’ category of sensitivity. Where there is
low risk of adverse outcomes, unrestricted publication of sensitive
species data remains appropriate. See the published guide
`https://doi.org/10.15468/doc-5jp4-5g10[Current Best Practices for
Generalizing Sensitive Species Occurrence Data]' for guidance on when
and how to generalize or withhold information sensitive biodiversity
data (Chapman 2020). The guide is also available in
https://docs.gbif.org/sensitive-species-best-practices/master/fr/[French]
and
https://docs.gbif.org/sensitive-species-best-practices/master/es/[Spanish].

*Reporting data generalizations*

When generalizing data you should try not to reduce the value of the
data for analysis, and a clear summary of the data generalization
process should be reported at the appropriate event level(s) using
http://rs.tdwg.org/dwc/terms/dataGeneralizations[_dwc:dataGeneralizations_].

For example, if the spatial resolution of locality data for an event is
reduced to the nearest half degree, then
http://rs.tdwg.org/dwc/terms/dataGeneralizations[_dwc:dataGeneralizations_]
= `__Coordinates generalized from original GPS coordinates to the
nearest half degree grid cell__' for each event to which this treatment
was applied. If the location information was generalized for every
sampling event site in a nested hierarchy, then at the parent event
level
http://rs.tdwg.org/dwc/terms/dataGeneralizations[_dwc:dataGeneralizations_]
= `__Coordinates for each event site generalized from original GPS
coordinates to the nearest half degree grid cell__.'

*Reporting information withheld*

If specific data are not reported with the dataset, a clarifying
statement should be provided at the appropriate event level using
http://rs.tdwg.org/dwc/terms/informationWithheld[_dwc:informationWithheld_].

For example, if sensitive species data are not purposefully excluded
from the published data,
http://rs.tdwg.org/dwc/terms/informationWithheld[_dwc:informationWithheld_]
should include a statement along the lines of `__Sensitive species
occurrence information not reported__.'

==== Least specific target category quantity inclusive

The term
http://rs.tdwg.org/eco/terms/isLeastSpecificTargetCategoryQuantityInclusive[_eco:isLeastSpecificTargetCategoryQuantityInclusive_]
provides a means by which to indicate to data users if an organismal
occurrence record for an specific event reporting an explicit quantity
of that organism via the paired terms
http://rs.tdwg.org/dwc/terms/organismQuantity[_dwc:organismQuantity_]
and
http://rs.tdwg.org/dwc/terms/organismQuantityType[_dwc:organismQuantityType_]
represents the total number of that organism observed during the event.
That is, it answers the question: _is this the only record of that
organism during the event?_

* If the quantity reported using these paired terms includes all the
organisms of the same taxon sampled/observed in that single occurrence
record, then
http://rs.tdwg.org/eco/terms/isLeastSpecificTargetCategoryQuantityInclusive[_eco:isLeastSpecificTargetCategoryQuantityInclusive_]
= `true.' +
* If the quantity reported using these paired terms does _not_ include
all organisms of the same taxon sampled/observed in that single
occurrence record (e.g., there are 2 or more occurrence records reported
for the same event), then
http://rs.tdwg.org/eco/terms/isLeastSpecificTargetCategoryQuantityInclusive[_eco:isLeastSpecificTargetCategoryQuantityInclusive_]
= `false.'

See https://eco.tdwg.org/inclusive/[Guidelines for
_eco:isLeastSpecificTargetCategoryQuantityInclusive_] (TDWG Humboldt
Extension Task Group 2024) for more information.

==== Verbatim fields

Two verbatim fields are available to provide additional information
about an event.

* *Field notes:* Field notes can be copied, transcribed verbatim, or
linked into http://rs.tdwg.org/dwc/terms/fieldNotes[_dwc:fieldNotes_]. +
* *Event remarks*: Additional comments about a particular Event that
don’t fit in any other term can be shared using
http://rs.tdwg.org/dwc/terms/eventRemarks[_dwc:eventRemarks_].

Both fields can be applied to any event at any level.

Other survey protocol information and verbatim protocol terms, their
recommended usage (status), and example data entries.

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Recommended
|http://rs.tdwg.org/eco/terms/hasMaterialSamples[_eco:hasMaterialSamples_]
|`true' or `false'

| |http://rs.tdwg.org/eco/terms/hasVouchers[_eco:hasVouchers_] |`true'
or `false'

|
|http://rs.tdwg.org/eco/terms/isLeastSpecificTargetCategoryQuantityInclusive[_eco:isLeastSpecificTargetCategoryQuantityInclusive_]
|`true' or `false'

|Share if available
|http://rs.tdwg.org/eco/terms/materialSampleTypes[_eco:materialSampleTypes_]
|`wholeOrganism'

|
|http://rs.tdwg.org/eco/terms/voucherInstitutions[_eco:voucherInstitutions_]
|`AMNH'

|
|_http://rs.tdwg.org/dwc/terms/dataGeneralizations[dwc:dataGeneralizations]_
|`Coordinates generalized from original GPS coordinates to the nearest
half degree grid cell.'; `Coordinates for each event site generalized
from original GPS coordinates to the nearest half degree grid cell'

|
|_http://rs.tdwg.org/dwc/terms/informationWithheld[dwc:informationWithheld]_
|`Sensitive species occurrence information not reported'

| |http://rs.tdwg.org/dwc/terms/fieldNotes[_dwc:fieldNotes_] |`Notes
available in the Grinnell-Miller Library'

| |http://rs.tdwg.org/dwc/terms/eventRemarks[_dwc:eventRemarks_] |
|===

=== Scope and completeness

*Survey scope* relates the biodiversity targeted (or not targeted)
during a survey. Structured reporting of explicitly stated survey scopes
is necessary for evaluating and reporting completeness and is critical
to understanding if the data can be used to assert absences
(non-detections) of taxa. *Completeness* indicates the thoroughness of a
survey relative to the stated scope. Structured reporting of explicitly
stated survey scopes and completeness is necessary for evaluating and
reporting completeness and is critical to understanding if the data can
be used to assert absences (non-detections) of taxa. Reported scope and
completeness information facilitates the ability of downstream data
users to interpret species populations, areas of occupancy, infer
species absences, etc.

Scope terms can be applied at any event level and recommended best
practice is to report as much information as is explicitly available but
only at the event levels for which the information is relevant
(information should not be inferred up or down an event hierarchy).

[width="100%",cols="<100%",options="header",]
|===
|NOTE: The `target' and `excluded' scope terms (e.g.,
_eco:targetTaxonomicScope_) presented in this section are the only
survey event terms designed to capture _intent_. That is, these terms
capture the breadth of the information the biological survey _intended_
to capture. All other terms should be used to report the actuality of
the survey (e.g., what protocol was in practice implemented, and what
information was actually collected).
|===

*Verbatim scope*

The full verbatim scope explicitly identifying the full suite of stated
parameters defining the breadth of a sampling event should be reported
using
http://rs.tdwg.org/eco/terms/verbatimTargetScope[_eco:verbatimTargetScope_].
_eco:verbatimTargetScope_ is particularly useful for capturing scope
conditions not covered by existing
https://eco.tdwg.org/terms/#taxonomic-scope[taxonomic] or
https://eco.tdwg.org/terms/#organismal-scope[organismal] scope terms.

General scope terms, their recommended usage (status), and example data
entries.

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Recommended
|http://rs.tdwg.org/eco/terms/verbatimTargetScope[_eco:verbatimTargetScope_]
|`Adult flying insects'
|===

==== Taxonomic scope

Providing taxonomic scope enables reliable, quantitative,
incl. statistical interpretation of survey and monitoring data. It is
essential to interpret local non-detection as local absences. An
explicitly stated targeted or intentionally excluded *taxonomic scope*
should be reported using
http://rs.tdwg.org/eco/terms/targetTaxonomicScope[__eco:targetTaxonomicScop__e]
and
http://rs.tdwg.org/eco/terms/excludedTaxonomicScope[_eco:excludedTaxonomicScope_].

* If a specific person(s) or organization(s) are recorded as making the
taxonomic identifications relevant to the stated survey scope(s), they
should be acknowledged using
http://rs.tdwg.org/dwc/terms/identifiedByID[_dwc:identifiedBy_] (for one
or more names) or
http://rs.tdwg.org/dwc/terms/identifiedByID[_dwc:identifiedByID_] (for
one or more unique identifiers such as, OrcID). +
* If every organism included in
http://rs.tdwg.org/eco/terms/targetTaxonomicScope[__eco:targetTaxonomicScop__e]
that was observed during an event was reported, then
http://rs.tdwg.org/eco/terms/isTaxonomicScopeFullyReported[_eco:isTaxonomicScopeFullyReported_]
= `true'; if not,
http://rs.tdwg.org/eco/terms/isTaxonomicScopeFullyReported[_eco:isTaxonomicScopeFullyReported_]
= `false'.

*Knowledge about taxonomic completeness* allows data users to determine
how comprehensively an area was sampled. If taxonomic completeness is
known
http://rs.tdwg.org/eco/terms/taxonCompletenessReported[_eco:taxonCompletenessReported_]
= `reportedComplete' or `reportedIncomplete' and the method used to
assess completeness reported in
_http://rs.tdwg.org/eco/terms/taxonCompletenessProtocols[eco:taxonCompletenessProtocols]_.
If taxonomic completeness is not reported,
http://rs.tdwg.org/eco/terms/taxonCompletenessReported[_eco:taxonCompletenessReported_]
= `notReported'.

Taxonomic scope terms, their recommended usage (status), and example
data entries.

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Recommended
|_http://rs.tdwg.org/eco/terms/targetTaxonomicScope[eco:targetTaxonomicScop]_http://rs.tdwg.org/eco/terms/targetTaxonomicScope[e]
|`Arthropods'

|
|_http://rs.tdwg.org/eco/terms/excludedTaxonomicScope[eco:excludedTaxonomicScope]_
|’Aves

|Share if available
|_http://rs.tdwg.org/dwc/terms/identifiedByID[dwc:identifiedBy]_
|’Cecilie Svenningsen

| |_http://rs.tdwg.org/dwc/terms/identifiedByID[dwc:identifiedByID]_
|https://orcid.org/0000-0002-9216-2917

|
|_http://rs.tdwg.org/eco/terms/isTaxonomicScopeFullyReported[eco:isTaxonomicScopeFullyReported]_
|`true' or `false'

|
|_http://rs.tdwg.org/eco/terms/taxonCompletenessReported[eco:taxonCompletenessReported]_
|`reportedComplete', `reportedIncomplete', or `notReported'

|
|_http://rs.tdwg.org/eco/terms/taxonCompletenessProtocols[eco:taxonCompletenessProtocols]_
|`Based on sampling effort'
|===

==== Organismal scope

As with taxonomic scope, providing organismal scope information when
relevant enables reliable, quantitative interpretation of survey and
monitoring data and can be essential to interpreting local non-detection
as local absences.

Three categories of terms are available by which to report an explicitly
stated target or excluded *organismal scope*, and state whether or not
all target organisms observed were reported. Other organismal scopes
should be reported using _eco:verbatimTargetScope_
(http://rs.tdwg.org/eco/terms/verbatimTargetScope).

*Life stage*

Life stage refers to the age class(es) or life stage(s) targeted for or
excluded from sampling.

* If the survey targeted or excluded specific organismal life stages,
the information should be reported in
http://rs.tdwg.org/eco/terms/targetLifeStageScope[_eco:targetLifeStageScope_]
and
http://rs.tdwg.org/eco/terms/excludedLifeStageScope[_eco:excludedLifeStageScope_]. +
* If every organism that was included within the life stage scope, and
was detected during the survey, was reported, then
http://rs.tdwg.org/eco/terms/isLifeStageScopeFullyReported[_eco:isLifeStageScopeFullyReported_]
= `true'. Otherwise,
http://rs.tdwg.org/eco/terms/isLifeStageScopeFullyReported[_eco:isLifeStageScopeFullyReported_]
= `false'.

A corresponding http://rs.tdwg.org/dwc/terms/lifeStage[_dwc:lifeStage_]
term is available in the Occurrence extension. This term can be used to
report life stage information for organism occurrences in the
`occurrence' table.

*Growth form*

Growth form refers to the physical characters or habits of an organism
in a given environment.

* If the survey targeted or excluded specific organismal growth forms,
the information should be reported in
http://rs.tdwg.org/eco/terms/targetGrowthFormScope[_eco:targetGrowthFormScope_]
and
http://rs.tdwg.org/eco/terms/isGrowthFormScopeFullyReported[_eco:isGrowthFormScopeFullyReported_]_http://rs.tdwg.org/eco/terms/excludedLifeStageScope[e]_. +
* If every organism that was included within the growth form scope, and
was detected during the survey, was reported, then
http://rs.tdwg.org/eco/terms/excludedGrowthFormScope[_eco:excludedGrowthFormScope_]
= `true'. Otherwise,
http://rs.tdwg.org/eco/terms/excludedGrowthFormScope[_eco:excludedGrowthFormScope_]
= `false'.

*Degree of establishment*

Degree of establishment refers to `The degree to which a dwc:Organism
survives, reproduces, and expands its range at the given place and time'
(see
http://rs.tdwg.org/dwc/terms/degreeOfEstablishment[_dwc:degreeOfEstablishment_]).

* If the survey targeted or excluded specific organismal degree of
establishment, the information should be reported in
http://rs.tdwg.org/eco/terms/targetDegreeOfEstablishmentScope[_eco:targetDegreeOfEstablishmentScope_]
and
http://rs.tdwg.org/eco/terms/excludedDegreeOfEstablishmentScope[_eco:excludedDegreeOfEstablishmentScope_]. +
* If every organism that was included within the degree of
establishment, and was detected during the survey, was reported, then
http://rs.tdwg.org/eco/terms/isDegreeOfEstablishmentScopeFullyReported[_eco:isDegreeOfEstablishmentScopeFullyReported_]
= `true'. Otherwise,
http://rs.tdwg.org/eco/terms/isDegreeOfEstablishmentScopeFullyReported[_eco:isDegreeOfEstablishmentScopeFullyReported_]
= `false.'

A corresponding
http://rs.tdwg.org/dwc/terms/degreeOfEstablishment[_dwc:degreeOfEstablishment_]
term is available in the Occurrence extension. This term can be used to
report degree of establishment information for organism occurrences in
the `occurrence' table.

Organismal scope terms, their recommended usage (status), and example
data entries.

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Share if available
|http://rs.tdwg.org/eco/terms/targetLifeStageScope[_eco:targetLifeStageScope_]
|`larva'

|
|http://rs.tdwg.org/eco/terms/excludedLifeStageScope[_eco:excludedLifeStageScope_]
|’adult

|
|http://rs.tdwg.org/eco/terms/isLifeStageScopeFullyReported[_eco:isLifeStageScopeFullyReported_]
|`true' or `false'

|
|http://rs.tdwg.org/eco/terms/targetDegreeOfEstablishmentScope[_eco:targetDegreeOfEstablishmentScope_]
|`native'

|
|http://rs.tdwg.org/eco/terms/excludedDegreeOfEstablishmentScope[_eco:excludedDegreeOfEstablishmentScope_]
|`invasive'

|
|http://rs.tdwg.org/eco/terms/isDegreeOfEstablishmentScopeFullyReported[_eco:isDegreeOfEstablishmentScopeFullyReported_]
|`true' or `false'

|
|http://rs.tdwg.org/eco/terms/targetGrowthFormScope[_eco:targetGrowthFormScope_]
|`tree'

|
|http://rs.tdwg.org/eco/terms/excludedGrowthFormScope[_eco:excludedGrowthFormScope_]
|`shrub'

|
|http://rs.tdwg.org/eco/terms/isGrowthFormScopeFullyReported[_eco:isGrowthFormScopeFullyReported_]
|`true' or `false'
|===

==== Bycatch

*Bycatch* is organisms detected during a survey that were not explicitly
targeted in the scope of a study. Bycatch, or a lack thereof, in a
dataset can be reported at the taxonomic and organismal levels.

If *_taxonomic_* bycatch are included in the datasets:

* Populate
http://rs.tdwg.org/eco/terms/hasNonTargetTaxa[_eco:hasNonTargetTaxa_] as
true at all relevant event levels. +
* If ALL *_taxonomic_* bycatch (_eco:hasNonTargetTaxa_ = `true')
captured/observed during an Event are reported in the dataset
** http://rs.tdwg.org/eco/terms/areNonTargetTaxaFullyReported[_eco:areNonTargetTaxaFullyReported_]
= `true' +
** and a list of taxonomic bycatch should be provided in
http://rs.tdwg.org/eco/terms/nonTargetTaxa[_eco:nonTargetTaxa_].

If *_organismal_* bycatch are included in the dataset:

* Then
http://rs.tdwg.org/eco/terms/hasNonTargetTaxa[_eco:hasNonTargetOrganisms_]
= `true' at all relevant event levels.

If the dataset does NOT include taxonomic or organismal bycatch:

* Populate
http://rs.tdwg.org/eco/terms/hasNonTargetTaxa[_eco:hasNonTargetTaxa_]
and
http://rs.tdwg.org/eco/terms/hasNonTargetTaxa[_eco:hasNonTargetOrganisms_]
as `false' for all relevant events.

Bycatch terms, their recommended usage (status), and example data
entries.

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Share if available
|http://rs.tdwg.org/eco/terms/hasNonTargetTaxa[_eco:hasNonTargetTaxa_]
|`true' or `false'

|
|http://rs.tdwg.org/eco/terms/areNonTargetTaxaFullyReported[_eco:areNonTargetTaxaFullyReported_]
|`true' or `false'

| |http://rs.tdwg.org/eco/terms/nonTargetTaxa[_eco:nonTargetTaxa_]
|’Parabuteo unicinctus

|
|http://rs.tdwg.org/eco/terms/hasNonTargetTaxa[_eco:hasNonTargetOrganisms_]
|`true' or `false'
|===

==== Habitat scope

If the survey includes an explicitly stated targeted or excluded
*habitat scope* these can be reported using the terms
http://rs.tdwg.org/eco/terms/targetHabitatScope[_eco:targetHabitatScope_]
and
http://rs.tdwg.org/eco/terms/excludedHabitatScope[_eco:excludedHabitatScope_].

The actual habitat observed at a survey site during a sampling event
should be reported in
http://rs.tdwg.org/dwc/terms/habitat[_dwc:habitat_].

Habitat scope terms, their recommended usage (status), and example data
entries.

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Share if available
|http://rs.tdwg.org/eco/terms/targetHabitatScope[_eco:targetHabitatScop_]
|`deciduous forest'

|
|http://rs.tdwg.org/eco/terms/excludedHabitatScope[_eco:excludedHabitatScope_]
|`urban'
|===

=== Sampling Effort

*Sampling effort* communicates sampling intensity during a sampling
event. Clear reporting of sampling effort is necessary to interpret
measures of completeness and calculate abundance (relative or absolute)
or biomass and is critical in assessing the ability to compare
information and aggregate data across studies.

The DwC event term
http://rs.tdwg.org/dwc/terms/samplingEffort[_dwc:samplingEffort_] is
currently a recommended field when publishing event datasets to GBIF,
however, this term captures sampling effort in an unstructured way. The
Humboldt extension includes 5 terms to more explicitly capture sampling
effort information. The updated r**_ecommended best practice_** is to
capture sampling effort information as structured data using the 5 terms
from the Humboldt Extension. Through these terms, data providers may
explicitly provide the following information:

* *Is sampling effort reported?:* indicate if sampling effort is
reported using the Boolean term
http://rs.tdwg.org/eco/terms/isSamplingEffortReported[_eco:isSamplingEffortReported_], +
* *Sampling effort protocol:*
*http://rs.tdwg.org/eco/terms/samplingEffortProtocol[eco:samplingEffortProtocol*]
should contain a textual description of the sampling effort protocol
(e.g., number and arrangement of people or sensors deployed, whether or
not sensors were mobile or stationary, how frequently observation,
measurements, or samples were taken) and/or provide a link to the
protocol used. +
* *Sampling effort:* report sampling effort (the total amount of time of
the sampling Event) value and units (e.g., 4 trap nights) using
http://rs.tdwg.org/eco/terms/samplingEffortValue[_eco:samplingEffortValue_]
and
http://rs.tdwg.org/eco/terms/samplingEffortUnit[_eco:samplingEffortUnit_],
and +
* *Sampling performed by:*
http://rs.tdwg.org/eco/terms/samplingPerformedBy[_eco:samplingPerformedBy_]
should be used to credit the people involved in the sampling
eventSampling effort terms, their recommendation usage, and example data
entries. Best practice is to use a unique identifier (e.g., OrcID) if
available.
** NOTE: Because
http://rs.tdwg.org/eco/terms/samplingPerformedBy[_eco:samplingPerformedBy_]
has an IRI equivalent only a single OrcID can be provided (the term
cannot support a list). Efforts are underway to enable the use of
dwc:http://rs.tdwg.org/dwc/terms/recordedByID[recordedByID] at the event
level so a list of OrcID’s (using the pipe separator between values) can
be provided.

[width="100%",cols="<100%",options="header",]
|===
|Updated r__ecommended best practice__ Capture sampling effort
information as structured data using the five (5) Humboldt extension
terms:
http://rs.tdwg.org/eco/terms/isSamplingEffortReported[_eco:isSamplingEffortReported_]
http://rs.tdwg.org/eco/terms/samplingEffortValue[_eco:samplingEffortValue_]
and
http://rs.tdwg.org/eco/terms/samplingEffortUnit[_eco:samplingEffortUnit_]
http://rs.tdwg.org/eco/terms/samplingEffortProtocol[_eco:samplingEffortProtocol_]
http://rs.tdwg.org/eco/terms/samplingPerformedBy[_eco:samplingPerformedBy_]
|===

Sampling effort terms, their recommended usage (status), and example
data entries.

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Recommended
|http://rs.tdwg.org/eco/terms/isSamplingEffortReported[_eco:isSamplingEffortReported_]
|`true' or `false'

|
|_http://rs.tdwg.org/eco/terms/samplingEffortProtocol[eco:samplingEffortProtocol]_
|`40 box traps deployed in the afternoon even spacings along 4 parallel
100m transects placed 50m apart and visited after sunrise the next day'

|
|_http://rs.tdwg.org/eco/terms/samplingEffortValue[eco:samplingEffortValue]_
|`40'

|
|_http://rs.tdwg.org/eco/terms/samplingEffortValue[eco:samplingEffortValue]_
|`trap nights'

| |_http://rs.tdwg.org/dwc/terms/samplingEffort[dwc:samplingEffort]_
|`40 trap nights'

|
|_http://rs.tdwg.org/eco/terms/samplingPerformedBy[eco:samplingPerformedBy]_
|`A. Townsend Peterson'
|===
