[[survey-event-data:-capturing-the-context-of-biological-surveys]]
== Survey event data: capturing the context of biological surveys

The following sections will guide you through the process of mapping
Event level information specifically related to survey structure,
location, protocols, scopes, and efforts.

[IMPORTANT]
.*Survey level information in DWC-A files*
====
Survey event data should be
saved to the DwC-A event table. This includes DwC Event terms (any term
preceded by _`dwc`_, e.g.,
term:dwc[dwc:eventID]) and Humboldt
extension terms (any term preceded by _`eco`_, e.g.,
term:eco[eco:protocolNames]).

  - A
comprehensive list of Darwin Core terms that can be applied at the event
level can be found on the Darwin Core Event page in the GBIF Registry of
Schemas (https://rs.gbif.org/core/dwc_event_2024-02-19.xml). 
  - The full
suite of Humboldt Extension terms is available on the Humboldt
Ecological Inventories page in the GBIF Registry of Schemas
(https://rs.gbif.org/extension/eco/Humboldt_2024-04-16.xml) and in the
Humboldt Extension Quick Reference Guide (https://eco.tdwg.org/terms/).

Fields for which there is no data to share at any hierarchical level can
be left blank or simply not included in the Event table. Populating
terms across event levels (e.g., from parent event to child event) 

Each event level can have its own set of attributes and measurements, which
can be captured using the Humboldt and/or other Extension(s) and be
unambiguously linked to the corresponding level through the appropriate
__dwc:eventID__s. 

A parent Event should not be populated by deriving or
summarizing information from child Events; rather, fields SHOULD be
populated explicitly with information directly appropriate to the nature
and level of the event itself (see Section _3.2.3 Principle of
non-derivation_ in the `https://eco.tdwg.org/hierarchy/[Properties of
hierarchical events in the Humboldt Extension for Ecological
Inventories]'). 

A child event SHOULD NOT implicitly inherit the value of
any property of any of its parent Event(s). If a value is in common
between an Event and its parent, the value should be included explicitly
in both Event records. 

Refer to https://eco.tdwg.org/hierarchy/[Properties of hierarchical events in the
Humboldt Extension for Ecological Inventories^] for guidance in
populating Humboldt extension terms across event levels.
====

=== Survey design

Survey sampling design specifies survey strategy and how the stations or
transects are laid out. Historically, only 2 terms were available to
explicitly structure and relate different levels of survey design in a
dataset: term:dwc[dwc:eventID] and
term:dwc[dwc:parentEventID]. One
additional Darwin Core event term,
term:dwc[dwc:fieldNumber], provided a
means by which to relate a sampling event with a dataset- or project-
specific field number. Humboldt extension provides an additional 2
terms—term:eco[eco:siteCount] and
term:eco[eco:siteNestingDescription]—
to better support complex or nested dataset.

[NOTE]
.*Event data in GBIF*
====
- Any dataset to be published using the DwC event core
must have at least 1 event record with a unique
term:dwc[dwc:eventID].
- Each term:dwc[dwc:eventID] in a dataset must be
unique within the dataset. Use of a persistent globally unique
identifier (GUID) is recommended (this can be the original field
number). A unique term:dwc[dwc:eventID]
should be reused between datasets where appropriate (for example, where
data collected during the same sampling event are published as multiple
datasets). See
https://assets.ctfassets.net/uo17ejk9rkwj/8aIUAbLo0oycyMiM2IKUS/363edf7ab4558460cfe1ef140567450f/persistent_identifiers_guide_en_v1.pdf[A
Beginner’s Guide to Persistent Identifiers] for guidance in creating
persistent identifiers. 
- An event is not required to have associated
organism occurrence data. If organism occurrence or non-detection data
are available, they are connected via the
term:dwc[dwc:eventID] to the event and the
https://rs.gbif.org/core/dwc_occurrence_2024-02-23.xml[Occurrence
extension]. 
- DwC event core extensions, including
https://rs.gbif.org/core/dwc_occurrence_2024-02-23.xml[occurrence],
https://rs.gbif.org/extension/obis/extended_measurement_or_fact_2023-08-28.xml[extended
measurements or facts], and
https://rs.gbif.org/extension/gbif/1.0/releve_2016-05-10.xml[Relevé]
extensions, can be applied to any event level via the appropriate
term:dwc[dwc:eventID].
====

*Non-nested datasets*

* Each event in a non-nested dataset must be assigned a unique
term:dwc[dwc:eventID]. +
* Non-nested datasets will not have a
term:dwc[dwc:parentEventID] and
term:eco[eco:siteNestingDescription]
does not need to be populated.

*Nested datasets*

Nested hierarchies are established by relating a child event to a parent
event through the child Event’s
term:dwc[dwc:parentEventID]. As
such, these more complex datasets require use of both
term:dwc[dwc:eventID] and
term:dwc[dwc:parentEventID].

* Each event in a nested dataset must have a unique
term:dwc[dwc:eventID]. +
* Each parent event must have its own
term:dwc[dwc:parentEventID].

In addition to event and parent event identifiers:

* *Site count and site nesting description:* Nested datasets should, at
the parent event level, include the total number of sites sampled in
term:eco[eco:siteCount] and provide a
textual description of the survey design or site sampling structure
using
term:eco[eco:siteNestingDescription]. +
* *Field number:* If the survey data include a field number for each
specific event, this should be shared using
term:dwc[dwc:fieldNumber].

[caption=]
.Event hierarchy terms, their recommended usage (status), and example data entries.
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Required |term:dwc[dwc:eventID]
|survey2022_a-2

|Required for nested datasets
|term:dwc[dwc:parentEventID]
|survey2022

.2+|Recommended
|term:eco[eco:siteCount]
|75

|term:eco[eco:siteNestingDescription]
|25 survey sites each with 3 1m2 quadrats

|Share if available
|term:dwc[dwc:fieldNumber] 
|RV Sol 87-03-08
|===



=== Survey site

An event *_site_* is the location at which observations are made or
samples and/or measurements are taken. Sharing thorough information
about a sampling event site, including description, locality, and
vegetative cover provides critical context to potential data users about
conditions in which survey was conducted. Information about the location
of each survey site including geographic coordinates with geodetic
datum, site description (locality name, habitat type, microhabitat), and
environmental data (e.g., physical parameters, vegetarian, water
quality) should be populated at every event level.

NOTE: The Darwin Core site terms listed in this section are not
comprehensive. Explore all Darwin Core Location class terms
(http://purl.org/dc/terms/Location) and the Humboldt Extension site
terms (https://eco.tdwg.org/terms/#site).

==== Site description

Context about a survey event site can be provided through a multitude of
terms that shared for every event level that the information is
available, including:

* *Site names:* report individual sampling event site names using
term:eco[eco:verbatimSiteNames].
A concatenated list of site names can be provided at higher event
levels. +
* *Habitat:* reported habitat at a sampling event site should be
recorded in term:dwc[dwc:habitat]. A
concatenated list of habitats can be provided at higher event levels. +
* *Weather:* reported weather at a sampling event site should be
recorded in
term:eco[eco:reportedWeather]. +
* *Extreme conditions:* reported extreme conditions at a sampling event
site at the time of the survey event should be recorded in
term:eco[eco:reportedExtremeConditions]. +
* *Verbatim site description:* verbatim comments (e.g., the original
textual description) about a site or sites should be copied in
term:eco[eco:verbatimSiteDescriptions].

These terms should be populated at any hierarchical event level that is
appropriate.

[caption=]
.General event site terms, their recommended usage (status), and example data entries
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
.5+|Share if available
|term:eco[eco:verbatimSiteNames]
|Trap_18\|Trap_27\|Trap_54\|Trap_96\|Annala\|Kumpula

|term:dwc[dwc:habitat]
|Ephemeral wetland

|term:eco[eco:reportedWeather]
|{"minimumTemperatureInDegreesFahrenheit": 18, "maximumTemperatureInDegreesFahrenheit": 32}

|term:eco[eco:reportedExtremeConditions]
|Site flooded

|term:eco[eco:verbatimSiteDescriptions]
|Coastal sand dunes at dry oak forest edge. Vegetation: Ammophila arenaria, Betula pendula, Leymus arenarius, Pinus sylvestris
|===

==== Site locality

The geographic location and extent of each survey event site should be
provided. Historically, 5 terms were strongly recommended for event
datasets in GBIF:

* *Location ID:* a unique identifier for each sampling event site should
be shared in
term:dwc[dwc:locationID]. +
* *Country code:* the two letter code for the country in which the
survey takes place should be provided in term:dwc[dwc:countryCode]. +
* *Latitude-Longitude:* The decimal latitude and longitude and geodetic
datum location of the Event site should be provided in term:dwc[dwc:decimalLatitude], term:dwc[dwc:decimalLongitude],
and term:dwc[dwc:geodeticDatum].
** If geographic coordinates are not in decimal latitude and decimal
longitude format, populate
term:dwc[dwc:verbatimLatitude],
term:dwc[dwc:verbatimLongitude],
and
term:dwc[dwc:verbatimCoordinateSystem]
instead.

The Humboldt extension includes additional terms that provide greater
contextual information about the geospatial scope of a sampling event or
series of events.

==== Survey site area

It is highly recommended to report additional information on the
targeted area and the area actually sampled to understand the geospatial
scope of the survey. Two sets of paired terms are available to report
the area of an event or survey site: _geospatial scope_ terms and _total
area sampled_ terms. *_Geospatial scope_* terms
(term:eco[eco:geospatialScopeAreaValue]
and
term:eco[eco:geospatialScopeAreaUnit])
define the geospatial scope or extent of a survey or sampling event.
*_Total area sampled_* terms
(term:eco[eco:totalAreaSampledValue]
and
term:eco[eco:totalAreaSampledUnit])
report the total area sampled during an event.

* For *non-nested event datasets*,
term:eco[eco:geospatialScopeAreaValue]
and
term:eco[eco:geospatialScopeAreaUnit],
and
term:eco[eco:totalAreaSampledValue]
and
term:eco[eco:totalAreaSampledUnit]
may contain the same values. +
* In *nested datasets*,
term:eco[eco:geospatialScopeAreaValue]
and
term:eco[eco:geospatialScopeAreaUnit]
should be used to report the full study extent at the parent event level
(the total area surveyed in a series of survey Events) and
term:eco[eco:totalAreaSampledValue]
and
term:eco[eco:totalAreaSampledUnit]
should be used to relate the area of child event sites (e.g., individual
survey sites). Geospatial scope value(s) should always be greater than
or equal to that of total area sampled.

For example, consider the
https://www.gbif.org/dataset/cd4eb3ec-0a18-42b4-bda4-155716ddd7b1[Biowide
project] which surveyed 130 40x40m plots across Denmark. Here, the
project-level parent event would report the full geographic extent of
Denmark:
term:eco[eco:geospatialScopeAreaValue]
= `42934` and
term:eco[eco:geospatialScopeAreaUnit]
= `km2`. The associated 130 child events representing each individual
survey site would then report the area of the site as
term:eco[eco:totalAreaSampledValue]
= `40` and
term:eco[eco:totalAreaSampledUnit]
= `m2`.

*_If the sampled unit is not an area_* (such as a filtered volume of
water in a zooplankton haul),
term:dwc[dwc:sampleSizeValue] and
term:dwc[dwc:sampleSizeUnit] should
be used in place of
term:eco[eco:totalAreaSampledValue]
and
term:eco[eco:totalAreaSampledUnit].

==== Additional survey site information

* *Survey site geometry:* If available, the geometry of a survey site
area should be shared using
term:dwc[dwc:footprintWKT] and
term:dwc[dwc:footprintSRS]. +
* *Verbatim site location information:* A more general text description
of the site location, if available, can be shared using
term:dwc[dwc:locality].

[caption=""]
.Event site geographic locality and scope terms and their recommended usage (status), namespace abbreviation, and example data entries.
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
.11+|Recommended
|*term:dwc[dwc:locationID*]
|`Trap_138`

|term:dwc[dwc:countryCode]
|`SE`

|term:dwc[dwc:decimalLatitude]
|`59.3168`

|term:dwc[dwc:decimalLongitude]
|`18.0627`

|term:dwc[dwc:geodeticDatum]
|`WGS84`

|term:eco[eco:geospatialScopeAreaValue]
|`580000`

|term:eco[eco:geospatialScopeAreaUnit]
|`km2`

|_term:eco[eco:totalAreaSampledValue]_
|`40`

|term:eco[eco:totalAreaSampledUnit]
|`m2`

|_term:dwc[dwc:sampleSizeValue]_
|`200`

|_term:dwc[dwc:sampleSizeUnit]_
|`m3`

.3+|Share if available
|term:dwc[dwc:footprintWKT]
|`POLYGON \((10 20, 11 20, 11 21, 10 21, 10 20))`

|term:dwc[dwc:footprintSRS]
|`epsg:4326`

|_term:dwc[dwc:locality]_ |`Agriculture site, Kongskilde Friluftsgård, Zealand`
|===

==== Vegetation cover

Vegetation cover at a survey site can be reported in three ways:

* *Verbatim vegetation cover:* a verbatim description of vegetation
cover can be captured in
term:eco[eco:verbatimSiteDescriptions]. +
* *Percent vegetation cover:* simple percent vegetation cover can be
recorded as structured data using the
https://rs.gbif.org/extension/obis/extended_measurement_or_fact_2023-08-28.xml[extended
measurements or facts extension]. +
* *Vegetation plot survey:* vegetation plot survey information can be
reported using the
https://rs.gbif.org/extension/gbif/1.0/releve_2016-05-10.xml[Relevé
extension].

If vegetation cover is reported, then
term:eco[eco:isVegetationCoverReported]
= `true`; otherwise,
term:eco[eco:isVegetationCoverReported]
= `false`.

=== Survey date and time

Complete and accurate reporting of the temporal scope of a survey is
crucial to asserting event structure and providing key contextual
information about sampling conditions.

*Event date, time, and duration*

Each event should have a reported date or date range reported in
term:dwc[dwc:eventDate] regardless of
its hierarchical level. *Nested datasets* should, at the parent event
level, report a date range encompassing all survey dates.

If available, the time and duration of each event should be reported
using term:dwc[dwc:eventTime] and the
paired terms
term:eco[eco:eventDurationValue]
and
term:eco[eco:eventDurationUnit].

Refer to GBIF’s technical documentation on
https://techdocs.gbif.org/en/data-processing/temporal-interpretation[Date
and time interpretation] for more guidance on reporting event dates and
times.

[caption=""]
.Event date and temporal scope terms, their recommended usage (status), and example data entries.
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Required
|term:dwc[dwc:eventDate]
|`2018-08-29`

.3+|Recommended
|_term:dwc[dwc:eventTime]_
|`08:00Z`


|term:eco[eco:eventDurationValue]
|`1`


|term:eco[eco:eventDurationUnit]
|`hour`
|===

=== Methodology/sampling protocol

*Sampling protocol* provides the details of how the sampling was
conducted. Clear communication of the sampling protocol implemented is
essential to ensuring the reliability, reproducibility, and reusability
of a dataset as detailed knowledge of survey methods facilitates data
integration and subsequent analysis.

[IMPORTANT]
====
Sampling protocol terms should be populated at every event level possible as inheritance in either direction should not be assumed or inferred between event levels.
====

==== Event type

Biological survey event data can result from a wide variety of effort
types (e.g., Bioblitzes, inventories). The nature of the survey event
should be reported using
term:dwc[dwc:eventType].

[NOTE]
.*Identifying event type*
====
term:dwc[dwc:eventType] should provide a high level overview of sampling effort type but should not be so specific as to overlap with sampling protocol. There is no single,
standardized vocabulary for term:dwc[dwc:eventType]. If your organization or community has a controlled vocabulary, it is recommended to apply terms from that. Otherwise, you can refer to the common event types below for guidance.

- *Project*: Projects are structured initiatives
with explicitly stated objective or suite of objectives and with clear
targets, timelines, and deliverables. Projects typically are typically
linked to non-biological information identifying participating
organizations and people (agents), funding agencies, and other
high-level administrative information. Biological sampling may only be
one facet of a project’s scope. `Project` as a
term:dwc[dwc:eventType] is typically
most appropriate only at the highest (parent) event level in a nested
dataset.
- *Expedition*: An expedition is an organized information gathering
venture that inherently includes multiple sampling events and event
types. Expeditions may include multiple taxonomic and/organismal scopes,
any number of documented sampling protocols, and varying degrees of
complexity in survey design. `Expedition` as a
term:dwc[dwc:eventType] is typically
most appropriate at higher (parent) event levels in nested hierarchies.
- *Survey*: A survey is a systematic effort to collect information about the
biological organisms in a specific area at a given time. Surveys
typically included at least one documented protocol and may or may not
have an explicitly defined taxonomic and/or organismal scope. `Survey`
is the most general event type term and can be applied as a
term:dwc[dwc:eventType] at any event
level.
- *Inventory*: An inventory is a comprehensive survey of the taxa
present in a specific area over an explicit period of time. Inventories
typically have an explicit taxonomic and/or organismal scope and a
well-defined protocol. `Inventory` is typically most appropriate as a
term:dwc[dwc:eventType] at lower (child)
event levels in nested hierarchies.
- *Bioblitz*: A bioblitz is a survey
event aimed at finding and identifying as many species as possible in a
specific area over a (typically) short, contiguous period of time.
Bioblitzes often include participants (agents) with a wide range of
backgrounds and levels of expertise in biodiversity sciences including
formal biologists as well as the broader, general public. `Bioblitz` as
a term:dwc[dwc:eventType] is typically
most appropriate at lower (child) event levels in nested hierarchies.
- *Identification*: An identification is the taxonomic identification of a
material sample or samples collected during an event. This could be an
identification by a professional taxonomist or through DNA analysis, but
it occurs at a time and place other than the survey site (e.g., a
laboratory).
====

*`Inventory` event types*

* If term:dwc[dwc:eventType] =
`inventory`, the type of search implemented (e.g., restricted search,
open search, opportunistic search, trap or sample, compilation) must be
reported in
term:eco[eco:inventoryTypes]. +
* If _eco:inventoryTypes_ = `compilation`, the compilation type should
be reported using
term:eco[eco:compilationTypes]
and data sources captured using
term:eco[eco:compilationSourceTypes].
** A compilation is a summary inventory resulting from the combination
of multiple existing inventories (as described in Guralnick et
al. 2018). Compilations are aggregates of multiple studies, and may
combine surveys employing different protocols, processes, and observers,
often with variable reporting of the methods employed or other compiled
data sources and literature searches.

[caption=""]
.Event type terms, their recommended usage (status), and example data entries
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Recommended |term:dwc[dwc:eventType]
|`Inventory`

.3+|Recommended if applicable
|term:eco[eco:inventoryTypes]
|`Open search`

|term:eco[eco:compilationTypes]
|`compilationOfExistingSourcesAndSamplingEvents`


|term:eco[eco:compilationSourceTypes]
|`museumSpecimens`
|===

==== Sampling protocol

Four protocol terms currently exist, however, only 1 term is required to
publish a sampling event dataset in GBIF:
term:dwc[dwc:samplingProtocol].
This requirement is because the initial Darwin Core event classification
only included the one term. The Humboldt Extension introduced 3 terms to
capture information about sampling protocol in a more structured manner:

* term:eco[eco:protocolNames] +
* term:eco[eco:protocolDescriptions] +
* term:eco[eco:protocolReferences]

[NOTE]
.*Updated recommended best practice*
====
- Report the name(s) of the sampling protocol with term:eco[eco:protocolNames].
- Capture details of the methods or protocols implemented using term:eco[eco:protocolDescriptions].
- Provide citation information for the protocol via term:eco[eco:protocolReferences].
- Retain term:dwc[dwc:samplingProtocol] as a verbatim field of term:eco[eco:protocolNames].
====

[caption=""]
.Survey event protocol terms, their recommended usage (status), and example data entries.
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Required
|term:dwc[dwc:samplingProtocol]
|`Visual survey`

.3+|Recommended
|term:eco[eco:protocolNames]
|`Visual survey`

|term:eco[eco:protocolDescriptions]
|`For each site a total list of lichen species (lichenized fungi) was produced based on a careful examination of soil, wood, stone surfaces and bark of trees up to 2 m at three time periods: October-November 2014, February-December 2015 and March and May 2016. Specimens that were not possible to identify with certainty in the field were sampled and subsequently identified in the laboratory. For each species the substrate, e.g. phorophyte (host) species was recorded. All records were registered in www.svampeatlas.dk, and the nomenclature used is in accordance with this database.`

|term:eco[eco:protocolReferences]
|`See Appendix B of Brunbjerg, A.K., Bruun, H.H., Brøndum, L. et al. A systematic survey of regional multi-taxon biodiversity: evaluating strategies and coverage. BMC Ecol 19, 43 (2019). https://doi.org/10.1186/s12898-019-0260-x \| https://doi.org/10.17504/protocols.io.kxygx3jwkg8j/v1`
|===

==== Absence and abundance

*Organismal absences* are defined here as the lack of detection of
organisms explicitly stated as part of the target taxonomic scope.
Absence information is critical to understanding species’ biogeography,
modeling species’ responses to climate- and human-induced environmental
change, and conservation planning and resource management.

* If the dataset includes absence information for one or more
occurrences (to be reported in the `occurrence` table as
_dwc:occurrenceStatus_ = `absent`), then
term:eco[eco:isAbsenceReported]
= `true`. +
* A list of absent taxa can be provided using
term:eco[eco:absentTaxa] at all
relevant levels. Absences should only be reported for taxa within the
stated taxonomic and/or organismal scope of a survey. Absence cannot be
asserted for bycatch.

See the section `link:#reporting-absences[Reporting absences]` for
details on reporting absence information at the occurrence level.

*Abundance* is the number of individuals of the same taxonomic
designation in a particular area at a specific time. Abundance data are
a key indicator of ecological health. They are necessary for conducting
biodiversity assessment, evaluating ecological health, managing invasive
species, and informing effective habitat and ecosystem management.

* If the dataset includes abundance information,
term:eco[eco:isAbundanceReported]
= `true` for all appropriate Event levels. If there is an abundance cap,
then
term:eco[eco:_isAbundanceCapReported]
= `true` and the value of the cap should be reported in
term:eco[eco:abundanceCap]. +
* If there is no abundance cap, then
term:eco[eco:_isAbundanceCapReported]
= `false`.

See the section `link:#abundance-information[Abundance information]` for
details on reporting absence information at the occurrence level.

[caption=""]
.Absence and abundance terms, their recommended usage (status), and example data entries.
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
.3+|Recommended
|term:eco[eco:isAbsenceReported]
|`true` or `false`


|term:eco[eco:isAbundanceReported]
|`true` or `false`


|term:eco[eco:isAbundanceCapReported]
|`true` or `false`

.2+|Share if available
|term:eco[eco:absentTaxa] |

|term:eco[eco:abundanceCap] |`5`
|===

==== Material samples

A *material sample* (http://rs.tdwg.org/dwc/terms/MaterialSample) is an
entity "…that represents an entity of interest in whole or in part."
Essentially, material samples are specimens collected during the survey
event. They may consist of an entire organism, part of an organism, or a
genetic sample.

If the dataset includes at least one material sample:

* term:eco[eco:hasMaterialSamples]
= `true` at the appropriate child event level and at any relevant parent
event level, and +
* the type(s) of materials collected should be listed under
term:eco[eco:materialSampleTypes]
for each relevant event level.

If the dataset or sampling event does _not_ include material samples:

* term:eco[eco:hasMaterialSamples]
= `false` at all appropriate sampling event levels.

==== Vouchers

A *voucher* is a specimen or material sample collected and accessioned
into a museum collection in support of a specific project or survey
effort.

If the dataset has vouchers:

* term:eco[eco:hasVouchers] = `true`
at the appropriate child event level and at any relevant parent event
level, and +
* a list of institutions housing them should be shared in
term:eco[eco:voucherInstitutions]
for each relevant event level.

If the dataset or sampling event does _not_ include vouchers:

* term:eco[eco:hasVouchers] = `false`
at all appropriate sampling event levels.

==== Sensitive data: data generalization & information withheld

Although the general recommendation is to share all biodiversity data
available at its highest spatio-temporal resolution, situations exist
where it is necessary to generalize data prior to sharing a dataset
publicly or even withhold information completely.

Two terms are available to communicate if data are generalized or
withheld from the data:
term:dwc[dwc:dataGeneralizations]
and
term:dwc[dwc:informationWithheld].
While it is the responsibility of the publisher to protect sensitive
species occurrence data, it is also the data publisher’s responsibility
to clearly communicate any relevant actions taken and to indicate if the
full data are available upon request..

How you generalize sensitive data (e.g. restrict the resolution of the
data) depends on the species’ category of sensitivity. Where there is
low risk of adverse outcomes, unrestricted publication of sensitive
species data remains appropriate. See the published guide
'https://doi.org/10.15468/doc-5jp4-5g10[Current Best Practices for
Generalizing Sensitive Species Occurrence Data]' for guidance on when
and how to generalize or withhold information sensitive biodiversity
data (Chapman 2020). The guide is also available in
https://docs.gbif.org/sensitive-species-best-practices/master/fr/[French]
and
https://docs.gbif.org/sensitive-species-best-practices/master/es/[Spanish].

*Reporting data generalizations*

When generalizing data you should try not to reduce the value of the
data for analysis, and a clear summary of the data generalization
process should be reported at the appropriate event level(s) using
term:dwc[dwc:dataGeneralizations].

For example, if the spatial resolution of locality data for an event is
reduced to the nearest half degree, then
term:dwc[dwc:dataGeneralizations]
= `Coordinates generalized from original GPS coordinates to the nearest half degree grid cell` for each event to which this treatment
was applied. If the location information was generalized for every
sampling event site in a nested hierarchy, then at the parent event
level
term:dwc[dwc:dataGeneralizations]
= `Coordinates for each event site generalized from original GPS coordinates to the nearest half degree grid cell`.

*Reporting information withheld*

If specific data are not reported with the dataset, a clarifying
statement should be provided at the appropriate event level using
term:dwc[dwc:informationWithheld].

For example, if sensitive species data are not purposefully excluded
from the published data,
term:dwc[dwc:informationWithheld]
should include a statement along the lines of `Sensitive species occurrence information not reported`.

==== Least specific target category quantity inclusive

The term
term:eco[eco:isLeastSpecificTargetCategoryQuantityInclusive]
provides a means by which to indicate to data users if an organismal
occurrence record for an specific event reporting an explicit quantity
of that organism via the paired terms
term:dwc[dwc:organismQuantity]
and
term:dwc[dwc:organismQuantityType]
represents the total number of that organism observed during the event.
That is, it answers the question: _is this the only record of that
organism during the event?_

* If the quantity reported using these paired terms includes all the
organisms of the same taxon sampled/observed in that single occurrence
record, then
term:eco[eco:isLeastSpecificTargetCategoryQuantityInclusive]
= `true` +
* If the quantity reported using these paired terms does _not_ include
all organisms of the same taxon sampled/observed in that single
occurrence record (e.g., there are 2 or more occurrence records reported
for the same event), then
term:eco[eco:isLeastSpecificTargetCategoryQuantityInclusive]
= `false`

See https://eco.tdwg.org/inclusive/[Guidelines for eco:isLeastSpecificTargetCategoryQuantityInclusive] (TDWG Humboldt Extension Task Group 2024) for more information.

==== Verbatim fields

Two verbatim fields are available to provide additional information
about an event.

* *Field notes:* Field notes can be copied, transcribed verbatim, or
linked into term:dwc[dwc:fieldNotes]. +
* *Event remarks*: Additional comments about a particular Event that
don’t fit in any other term can be shared using
term:dwc[dwc:eventRemarks].

Both fields can be applied to any event at any level.

[caption=""]
.Other survey protocol information and verbatim protocol terms, their recommended usage (status), and example data entries.
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
.3+|Recommended
|term:eco[eco:hasMaterialSamples]
|`true` or `false`

|term:eco[eco:hasVouchers]
|`true` or `false`

|term:eco[eco:isLeastSpecificTargetCategoryQuantityInclusive]
|`true` or `false`

.5+|Share if available
|term:eco[eco:materialSampleTypes]
|`wholeOrganism` \| `blood`

|term:eco[eco:voucherInstitutions]
|`AMNH` \| `KUNHM`

|_term:dwc[dwc:dataGeneralizations]_
|`Coordinates generalized from original GPS coordinates to the nearest half degree grid cell.`; `Coordinates for each event site generalized from original GPS coordinates to the nearest half degree grid cell`


|term:dwc[dwc:informationWithheld]
|`Sensitive species occurrence information not reported`

|term:dwc[dwc:fieldNotes] |`Notes available in the Grinnell-Miller Library`

|
|term:dwc[dwc:eventRemarks]
|
|===

=== Scope and completeness

*Survey scope* relates the biodiversity targeted (or not targeted)
during a survey. Structured reporting of explicitly stated survey scopes
is necessary for evaluating and reporting completeness and is critical
to understanding if the data can be used to assert absences
(non-detections) of taxa. *Completeness* indicates the thoroughness of a
survey relative to the stated scope. Structured reporting of explicitly
stated survey scopes and completeness is necessary for evaluating and
reporting completeness and is critical to understanding if the data can
be used to assert absences (non-detections) of taxa. Reported scope and
completeness information facilitates the ability of downstream data
users to interpret species populations, areas of occupancy, infer
species absences, etc.

Scope terms can be applied at any event level and recommended best
practice is to report as much information as is explicitly available but
only at the event levels for which the information is relevant
(information should not be inferred up or down an event hierarchy).

[NOTE]
====
The `target` and `excluded` scope terms (e.g., term:eco[eco:targetTaxonomicScope]) presented in this section are the only survey event terms designed to capture _intent_. That is, these terms capture the breadth of the information the biological survey _intended_ to capture. All other terms should be used to report the actuality of the survey (e.g., what protocol was in practice implemented, and what information was actually collected).
====

*Verbatim scope*

The full verbatim scope explicitly identifying the full suite of stated
parameters defining the breadth of a sampling event should be reported
using
term:eco[eco:verbatimTargetScope].
_eco:verbatimTargetScope_ is particularly useful for capturing scope
conditions not covered by existing
https://eco.tdwg.org/terms/#taxonomic-scope[taxonomic] or
https://eco.tdwg.org/terms/#organismal-scope[organismal] scope terms.

General scope terms, their recommended usage (status), and example data
entries.

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Recommended
|term:eco[eco:verbatimTargetScope]
|`Adult flying insects`
|===

==== Taxonomic scope

Providing taxonomic scope enables reliable, quantitative,
incl. statistical interpretation of survey and monitoring data. It is
essential to interpret local non-detection as local absences. An
explicitly stated targeted or intentionally excluded *taxonomic scope*
should be reported using
http://rs.tdwg.org/eco/terms/targetTaxonomicScope[__eco:targetTaxonomicScop__e]
and
term:eco[eco:excludedTaxonomicScope].

* If a specific person(s) or organization(s) are recorded as making the
taxonomic identifications relevant to the stated survey scope(s), they
should be acknowledged using
term:dwc[dwc:identifiedBy] (for one
or more names) or
term:dwc[dwc:identifiedByID] (for
one or more unique identifiers such as, OrcID). +
* If every organism included in
http://rs.tdwg.org/eco/terms/targetTaxonomicScope[__eco:targetTaxonomicScop__e]
that was observed during an event was reported, then
term:eco[eco:isTaxonomicScopeFullyReported]
= `true`; if not,
term:eco[eco:isTaxonomicScopeFullyReported]
= `false`.

*Knowledge about taxonomic completeness* allows data users to determine
how comprehensively an area was sampled. If taxonomic completeness is
known
term:eco[eco:taxonCompletenessReported]
= `reportedComplete` or `reportedIncomplete` and the method used to
assess completeness reported in
_term:eco[eco:taxonCompletenessProtocols]_.
If taxonomic completeness is not reported,
term:eco[eco:taxonCompletenessReported]
= `notReported`.

Taxonomic scope terms, their recommended usage (status), and example
data entries.

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Recommended
|_term:eco[eco:targetTaxonomicScop]_http://rs.tdwg.org/eco/terms/targetTaxonomicScope[e]
|`Arthropods`

|
|_term:eco[eco:excludedTaxonomicScope]_
|’Aves

|Share if available
|_term:dwc[dwc:identifiedBy]_
|’Cecilie Svenningsen

| |_term:dwc[dwc:identifiedByID]_
|https://orcid.org/0000-0002-9216-2917

|
|_term:eco[eco:isTaxonomicScopeFullyReported]_
|`true` or `false`

|
|_term:eco[eco:taxonCompletenessReported]_
|`reportedComplete`, `reportedIncomplete`, or `notReported`

|
|_term:eco[eco:taxonCompletenessProtocols]_
|`Based on sampling effort`
|===

==== Organismal scope

As with taxonomic scope, providing organismal scope information when
relevant enables reliable, quantitative interpretation of survey and
monitoring data and can be essential to interpreting local non-detection
as local absences.

Three categories of terms are available by which to report an explicitly
stated target or excluded *organismal scope*, and state whether or not
all target organisms observed were reported. Other organismal scopes
should be reported using _eco:verbatimTargetScope_
(http://rs.tdwg.org/eco/terms/verbatimTargetScope).

*Life stage*

Life stage refers to the age class(es) or life stage(s) targeted for or
excluded from sampling.

* If the survey targeted or excluded specific organismal life stages,
the information should be reported in
term:eco[eco:targetLifeStageScope]
and
term:eco[eco:excludedLifeStageScope]. +
* If every organism that was included within the life stage scope, and
was detected during the survey, was reported, then
term:eco[eco:isLifeStageScopeFullyReported]
= `true`. Otherwise,
term:eco[eco:isLifeStageScopeFullyReported]
= `false`.

A corresponding term:dwc[dwc:lifeStage]
term is available in the Occurrence extension. This term can be used to
report life stage information for organism occurrences in the
`occurrence` table.

*Growth form*

Growth form refers to the physical characters or habits of an organism
in a given environment.

* If the survey targeted or excluded specific organismal growth forms,
the information should be reported in
term:eco[eco:targetGrowthFormScope]
and
term:eco[eco:isGrowthFormScopeFullyReported]_http://rs.tdwg.org/eco/terms/excludedLifeStageScope[e]_. +
* If every organism that was included within the growth form scope, and
was detected during the survey, was reported, then
term:eco[eco:excludedGrowthFormScope]
= `true`. Otherwise,
term:eco[eco:excludedGrowthFormScope]
= `false`.

*Degree of establishment*

Degree of establishment refers to `The degree to which a dwc:Organism
survives, reproduces, and expands its range at the given place and time'
(see
term:dwc[dwc:degreeOfEstablishment]).

* If the survey targeted or excluded specific organismal degree of
establishment, the information should be reported in
term:eco[eco:targetDegreeOfEstablishmentScope]
and
term:eco[eco:excludedDegreeOfEstablishmentScope]. +
* If every organism that was included within the degree of
establishment, and was detected during the survey, was reported, then
term:eco[eco:isDegreeOfEstablishmentScopeFullyReported]
= `true`. Otherwise,
term:eco[eco:isDegreeOfEstablishmentScopeFullyReported]
= `false.`

A corresponding
term:dwc[dwc:degreeOfEstablishment]
term is available in the Occurrence extension. This term can be used to
report degree of establishment information for organism occurrences in
the `occurrence` table.

Organismal scope terms, their recommended usage (status), and example
data entries.

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Share if available
|term:eco[eco:targetLifeStageScope]
|`larva`

|
|term:eco[eco:excludedLifeStageScope]
|’adult

|
|term:eco[eco:isLifeStageScopeFullyReported]
|`true` or `false`

|
|term:eco[eco:targetDegreeOfEstablishmentScope]
|`native`

|
|term:eco[eco:excludedDegreeOfEstablishmentScope]
|`invasive`

|
|term:eco[eco:isDegreeOfEstablishmentScopeFullyReported]
|`true` or `false`

|
|term:eco[eco:targetGrowthFormScope]
|`tree`

|
|term:eco[eco:excludedGrowthFormScope]
|`shrub`

|
|term:eco[eco:isGrowthFormScopeFullyReported]
|`true` or `false`
|===

==== Bycatch

*Bycatch* is organisms detected during a survey that were not explicitly
targeted in the scope of a study. Bycatch, or a lack thereof, in a
dataset can be reported at the taxonomic and organismal levels.

If *_taxonomic_* bycatch are included in the datasets:

* Populate
term:eco[eco:hasNonTargetTaxa] as
true at all relevant event levels. +
* If ALL *_taxonomic_* bycatch (_eco:hasNonTargetTaxa_ = `true`)
captured/observed during an Event are reported in the dataset
** term:eco[eco:areNonTargetTaxaFullyReported]
= `true` +
** and a list of taxonomic bycatch should be provided in
term:eco[eco:nonTargetTaxa].

If *_organismal_* bycatch are included in the dataset:

* Then
term:eco[eco:hasNonTargetOrganisms]
= `true` at all relevant event levels.

If the dataset does NOT include taxonomic or organismal bycatch:

* Populate
term:eco[eco:hasNonTargetTaxa]
and
term:eco[eco:hasNonTargetOrganisms]
as `false` for all relevant events.

Bycatch terms, their recommended usage (status), and example data
entries.

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Share if available
|term:eco[eco:hasNonTargetTaxa]
|`true` or `false`

|
|term:eco[eco:areNonTargetTaxaFullyReported]
|`true` or `false`

| |term:eco[eco:nonTargetTaxa]
|’Parabuteo unicinctus

|
|term:eco[eco:hasNonTargetOrganisms]
|`true` or `false`
|===

==== Habitat scope

If the survey includes an explicitly stated targeted or excluded
*habitat scope* these can be reported using the terms
term:eco[eco:targetHabitatScope]
and
term:eco[eco:excludedHabitatScope].

The actual habitat observed at a survey site during a sampling event
should be reported in
term:dwc[dwc:habitat].

Habitat scope terms, their recommended usage (status), and example data
entries.

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Share if available
|term:eco[eco:targetHabitatScop]
|`deciduous forest`

|
|term:eco[eco:excludedHabitatScope]
|`urban`
|===

=== Sampling Effort

*Sampling effort* communicates sampling intensity during a sampling
event. Clear reporting of sampling effort is necessary to interpret
measures of completeness and calculate abundance (relative or absolute)
or biomass and is critical in assessing the ability to compare
information and aggregate data across studies.

The DwC event term
term:dwc[dwc:samplingEffort] is
currently a recommended field when publishing event datasets to GBIF,
however, this term captures sampling effort in an unstructured way. The
Humboldt extension includes 5 terms to more explicitly capture sampling
effort information. The updated r**_ecommended best practice_** is to
capture sampling effort information as structured data using the 5 terms
from the Humboldt Extension. Through these terms, data providers may
explicitly provide the following information:

* *Is sampling effort reported?:* indicate if sampling effort is
reported using the Boolean term
term:eco[eco:isSamplingEffortReported], +
* *Sampling effort protocol:*
*term:eco[eco:samplingEffortProtocol*]
should contain a textual description of the sampling effort protocol
(e.g., number and arrangement of people or sensors deployed, whether or
not sensors were mobile or stationary, how frequently observation,
measurements, or samples were taken) and/or provide a link to the
protocol used. +
* *Sampling effort:* report sampling effort (the total amount of time of
the sampling Event) value and units (e.g., 4 trap nights) using
term:eco[eco:samplingEffortValue]
and
term:eco[eco:samplingEffortUnit],
and +
* *Sampling performed by:*
term:eco[eco:samplingPerformedBy]
should be used to credit the people involved in the sampling
eventSampling effort terms, their recommendation usage, and example data
entries. Best practice is to use a unique identifier (e.g., OrcID) if
available.
** NOTE: Because
term:eco[eco:samplingPerformedBy]
has an IRI equivalent only a single OrcID can be provided (the term
cannot support a list). Efforts are underway to enable the use of
dwc:http://rs.tdwg.org/dwc/terms/recordedByID[recordedByID] at the event
level so a list of OrcID’s (using the pipe separator between values) can
be provided.

[width="100%",cols="<100%",options="header",]
|===
|Updated r__ecommended best practice__ Capture sampling effort
information as structured data using the five (5) Humboldt extension
terms:
term:eco[eco:isSamplingEffortReported]
term:eco[eco:samplingEffortValue]
and
term:eco[eco:samplingEffortUnit]
term:eco[eco:samplingEffortProtocol]
term:eco[eco:samplingPerformedBy]
|===

Sampling effort terms, their recommended usage (status), and example
data entries.

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Recommended
|term:eco[eco:isSamplingEffortReported]
|`true` or `false`

|
|_term:eco[eco:samplingEffortProtocol]_
|`40 box traps deployed in the afternoon even spacings along 4 parallel
100m transects placed 50m apart and visited after sunrise the next day'

|
|_term:eco[eco:samplingEffortValue]_
|`40`

|
|_term:eco[eco:samplingEffortValue]_
|`trap nights`

| |_term:dwc[dwc:samplingEffort]_
|`40 trap nights`

|
|_term:eco[eco:samplingPerformedBy]_
|`A. Townsend Peterson`
|===
