[[mapping-additional-survey-event-information:-dwc-extensions]]
== Mapping additional survey event information: DwC Extensions

=== Extended Measurement or Fact (eMoF)

Additional measurements about a site including values and units of
measurement and related protocols can be shared for any event level
using the extended measurement or fact extension (eMOF). The extension
was developed by the Ocean Biodiversity Information System (OBIS,
https://obis.org/), and detailed instructions about implementing the
extension are available in the OBIS manual
(https://manual.obis.org/format_emof.html).

eMoF extension information as a GBIF registered extension is available at https://rs.gbif.org/extension/obis/extended_measurement_or_fact_2023-08-28.xml.

=== Relevé extension

The Relevé extension
(https://rs.gbif.org/extension/gbif/1.0/releve_2016-05-10.xml) is
designed to capture vegetation plot survey measurements at a survey
site. The extension facilitates explicit reporting of:

* The description of the plant community associated the survey +
* Aspect and inclination at the survey site +
* Percent total cover of all plants and percent cover of trees, shrubs,
herbs, cryptograms, mosses, lichens, algae, litter, water, and rocks +
* Heights of tree, shrub, and herbaceous layers +
* Whether or not mosses or lichens are identified

[NOTE]
.*Using the Relevé extension* (https://rs.gbif.org/extension/gbif/1.0/releve_2016-05-10.xml) 
====
- Create a new `Relevé` table
- Add term:dwc[dwc:eventID] as a column header so to link the
record to the `Event` table.
- Add the Relevé extension fields as column headers. The term:dwc[dwc:eventID] will link the record to the `Event' table
- For each unique survey event (term:dwc[dwc:eventID]), populate the relevant extension field. Information for a unique term:dwc[dwc:eventID] should require only one row in the table.
====

For an example implementation of the Relevé extension
(https://rs.gbif.org/extension/gbif/1.0/releve_2016-05-10.xml), see the
example dataset https://doi.org/10.15468/pkx4tg[Vegetation plots
collected in dry grasslands throughout Bulgaria and Romanian Dobrudzha].

<<<
