== Mapping occurrence information

[IMPORTANT]
====
Occurrence information should be saved to a DWC-A `occurrence` file. 

See the data/event_template_wHE_occurrence-table.csv[occurrence] table in the data mapping template.
====

Each DwC Event can be associated with one or more Occurrence records of individual organisms or taxa. Occurrence information is mapped and linked to a survey Event using the https://rs.gbif.org/core/dwc_occurrence_2024-02-23.xml[DwC Occurrence extension]. Each Occurrence record can be mapped to only a single survey Event; however, Occurrence records can be link to any event level. In the case of a nested hierarchy, the recommended best practice is to link each Occurrence to the lowest possible event level to maintain specificity. Occurrence information should be contained in the 'occurrence' table of the DwC-A.

Each organism occurrence must include the following information:

* *Event ID:* A link the occurrence to the correct survey event with term:dwc[dwc:eventID]. +
* *Occurrence ID:* A unique term:dwc[dwc:occurrenceID]. +
* *Scientific name:* The most specific taxonomic identification of the organism in term:dwc[dwc:scientificName]. +
* *Basis of record:* The nature of the occurrence (e.g. human observation, material specimen) must be reported in term:dwc[dwc:basisOfRecord].

=== Reporting multiple individuals as a single occurrence

If multiple individuals of the same taxonomic classification are observed and no additional information about the organisms (e.g., life stage, sex) is collected other than taxonomic identification, report as a single occurrence (e.g., 1 row in the table), with the following information: 

* a unique term:dwc[dwc:occurrenceID], +
* taxonomic classification of the organisms reported in term:dwc[dwc:scientificName], and +
* the quantity and unit of organisms observed reported in the paired terms term:dwc[dwc:organismQuantity] and term:dwc[dwc:organismQuantityType].

For example, if four hooded crows (_Corvus cornix_) were observed, a single occurrence with one term:dwc[dwc:occurrenceID] should be reported.

[width="99%",cols="<20%,<16%,<16%,<16%,16%,16%",options="header",]
|===
|term:dwc[dwc:eventID]
|term:dwc[dwc:occurrenceID]
|term:dwc[dwc:basisOfRecord]
|term:dwc[dwc:scientificName]
|term:dwc[dwc:organismQuantity]
|term:dwc[dwc:organismQuantityType]
|`<uniqueEventID>`
|`<uniqueObsID>`
|`HumanObservation`
|`Corvus cornix`
|`4`
|`individuals`
|===

=== Reporting multiple individuals as multiple occurrences

If multiple individuals of the same taxonomic classification are observed and additional information about the organisms (e.g., life stage, sex) is collected, then a unique occurrence record (row in the table) should be created for each unique combination of taxonomic identification-organism traits.

For example, if 1 adult male and 3 adult females Indian gharials (_Gavialis gangeticus_) were observed alive, two occurrences, each with a unique term:dwc[dwc:occurrenceID] would be reported.

[width="99%",cols="<12%,<11%,<11%,<11%,11%,11%,11%,11%,11%",options="header",]
|===
|term:dwc[dwc:eventID]
|term:dwc[dwc:occurrenceID]
|term:dwc[dwc:basisOfRecord]
|term:dwc[dwc:scientificName]
|term:dwc[dwc:organismQuantity]
|term:dwc[dwc:organismQuantityType]
|term:dwc[dwc:sex]
|term:dwc[dwc:lifeStage]
|term:dwc[dwc:vitality]
|`uniqueEventID-1` 
|`uniqueObsID-1`
|`HumanObservation`
|`Gavialis gangeticus`
|`1`
|`individuals`
|`male` 
|`adult`
|`alive`

|`uniqueEventID-1`
|`uniqueObsID-2`
|`HumanObservation` 
|`Gavialis gangeticus`
|`3` 
|`individuals` 
|`female` 
|`adult` 
|`alive`
|===

The table below outlines the minimum required and recommended terms for each occurrence record, as well some of the more commonly used terms and their recommended usages. However, Darwin Core includes many more terms. It is advisable to take some time to review the DwC quick reference guide https://dwc.tdwg.org/terms/[DwC quick reference guide] to identify and include any and all terms available that allow you to share the richest version of your data possible. Sections that may be of particular interest:

* 'https://dwc.tdwg.org/terms/#occurrence[occurrence]'
* 'https://dwc.tdwg.org/terms/#identification[identification]'
* 'https://dwc.tdwg.org/terms/#taxon[taxon]'

[caption=""]
.Species occurrence terms, their recommended usage (status), and example data entries.
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
.4+|Required
|term:dwc[dwc:eventID]
|`uniqueEventID-1`

|term:dwc[dwc:occurrenceID]
|`uniqueObsID-2`

|term:dwc[dwc:scientificName]
|`Gavialis gangeticus`

|term:dwc[dwc:basisOfRecord]
|`HumanObservation`

.5+|Recommended
|term:dwc[dwc:taxonRank]
|`species`

|term:dwc[dwc:kingdom]
|`Animalia`

|term:dwc[dwc:organismQuantity]
|`3`

|term:dwc[dwc:organismQuantityType]
|`individuals`

|term:dwc[dwc:occurrenceStatus]
|`present` or `absent`

.6+|Share if available
|term:dwc[dwc:vernacularName]
|`Indian gharial`

|term:dwc[dwc:sex]
|`female`

|term:dwc[dwc:lifeStage]
|`adult`

|term:dwc[dwc:establishmentMeans]
|`native`

|term:dwc[dwc:degreeOfEstablishment]
|`native`

|term:dwc[dwc:vitality]
|`dead`
|===

=== Reporting absences

*Absences* are defined here as the lack of detection of organisms that are explicitly stated to be part of the target taxonomic scope. Information regarding the absence of detection of a type of taxon can be reported explicitly or implicitly within a DwC-A. When the taxonomic scope is highly constrained, for example being restricted to only one or a few taxa, it is feasible to include occurrence records for each of the non-detected taxa within the data, with each absence being denoted by setting dwc:OccurrenceStatus to `absent`. However, when taxonomic scopes are broader, and include hundreds or thousands of species (e.g., a taxonomic scope of a dataset that includes all species of birds in the world), then it becomes infeasible to add occurrence records of zero individuals for all of the species not detected.

The reporting of absences only provides useful information when term:eco[eco:isTaxonomicScopeFullyReported] is `true`. 

If term:eco[eco:isTaxonomicScopeFullyReported] is `false` then occurrence records of zero individuals are uninterpretable because the user of these data does not know whether there are any taxa that were not detected but were not reported with occurrence records of zero individuals. Implicit reporting of absences is impossible if term:eco[eco:isTaxonomicScopeFullyReported] is `false`.

If absences are implicitly reported, each end user of data will need to reconstruct explicit absences for themselves for each taxon of interest to them, because any unreported taxon (i.e. any taxon without an occurrence record) is known to be absent. Again, this will only be possible if term:eco[eco:isTaxonomicScopeFullyReported] is `true` and a taxonomic scope is reported.


*Explicit documentation of absences*

To document absences with a DwC-A by including zero-count occurrence records:

* In the `occurrence table`:
** For each occurrence to be reported absent, term:dwc[dwc:occurrenceStatus] = `absent`. +
** Recommended best practice is to also populate term:dwc[dwc:individualCount] and term:dwc[dwc:organismQuantity] as `0` and term:dwc[dwc:organismQuantityType] as `Individuals`. +
* In the `event table`:
** If one or more absences are reported at any taxonomic level (term:dwc[dwc:occurrenceStatus] = `absent`), then term:eco[eco:isAbsenceReported] = `true` at each relevant Event level.

* A list of absent taxa can be provided using term:eco[eco:absentTaxa] at all relevant Event levels.

Absences should only be reported for taxa within the stated taxonomic and/or organismal scope of a survey. Absence cannot be asserted for bycatch.

*Implicit documentation of absences*

To implicitly document absences in a DwC-A, term:eco[eco:isTaxonomicScopeFullyReported] must be `true`for the Event, and either term:eco[eco:targetTaxonomicScope] or term:eco[eco:excludedTaxonomicScope] must be specified. Then:
* In the `occurrence table`: +
** For each taxon to be implicitly reported absent, there will not be any Occurrence record created.
* In the `event table`: +
** Because no absences are explicitly reported, then term:eco[eco:isAbsenceReported] = `false` for parent Events at all relevant levels.

Absences should only be reported for taxa within the stated taxonomic and/or organismal scope of a survey. Absence cannot be asserted for bycatch.


[caption=""]
.Terms to indicate absence, or non-detection, and their recommendation usage.
[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Table |Recommended usage |Term |Example entry
|Occurrence
|Required
|term:dwc[dwc:occurrenceStatus]
|`present` or `absent`

|Occurrence
.5+|Recommended
|term:dwc[dwc:individualCount]
|`3`

|Occurrence
|term:dwc[dwc:organismQuantity]
|`3`

|Occurrence
|term:dwc[dwc:organismQuantityType]
|`individuals`

|Event
|term:eco[eco:isAbsenceReported]
|`true` or `false`

|Event
|term:eco[eco:isTaxonomicScopeFullyReported]
|`true` or `false`

|Event
|Share if available
|term:eco[eco:absentTaxa]
|
|===

=== Reporting abundance information

To capture abundance information in a dataset or at a specific event level:

* In the `occurrence table`, use the paired terms term:dwc[dwc:organismQuantity] and term:dwc[dwc:organismQuantityType] to report the observed abundance for each reported occurrence. For example, if 3 individuals of a species were observed:
** term:dwc[dwc:organismQuantity] = `3` +
** term:dwc[dwc:organismQuantityType] = `Individuals` +
* In the `event table`:
** The inclusion of abundance information in the datasett, even if this information is not reported for all taxa, should be indicated by populating term:eco[eco:isAbundanceReported] as `true`. +
** The existence of an abundance cap should be captured using the Boolean term term:eco[eco:isAbundanceCapReported] and the value of that cap reported in term:eco[eco:abundanceCap].

If the dataset or relevant event does not include abundance information, then it is recommended that the following terms be populated as follows in the `event table` at the appropriate level within the Event hierarchy:

* term:eco[eco:isAbundanceReported] = `false` +
* term:eco[eco:isAbundanceCapReported] = `false`

[caption=""]
.Terms to indicate abundance, the table on which they should be provided, and their recommendation usage.
[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Table |Recommended usage |Term |Example entry
|Occurrence
.5+|Recommended
|term:dwc[dwc:individualCount]
|`3`

|Occurrence
|term:dwc[dwc:organismQuantity]
|`3`

|Occurrence
|term:dwc[dwc:organismQuantityType]
|`individuals`

|Event
|term:eco[eco:isAbundanceReported]
|`true` or `false`

|Event
|term:eco[eco:isAbundanceCapReported]
|`true` or `false`

|Event
|Share if available
|term:eco[ecoabundanceCap]
|`5`
|===

=== Capturing species’ co-occurrence and species’ interactions

The https://rs.gbif.org/extension/resource_relationship_2024-02-19.xml[Resource Relationship extension] can be used to link information related across multiple occurrences (may be from the same or from different events), such as:

*An occurrence with another occurrence*

The table below highlights an example from the dataset https://doi.org/10.15468/xdzgbt[Potential host plant records recovered from ECOAB wild bee collection, Mexico] published by _Comisión nacional para el conocimiento y uso de la biodiversidad_. In this example, a _Bombus ephippiatus_ bee visits a species of runner bean, _Phaseolus coccineus_.

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Table |Recommended usage |Term |Example entry
|Occurrence
.3+|Required
|term:dwc[dwc:occurrenceID]
|`ECOSUR-SC:ECOAB:861`

|ResourceRelationship
|term:dwc[dwc:resourceID]
|`ECOSUR-SC:ECOAB:861`

|ResourceRelationship
|term:dwc[dwc:relatedResourceID]
|`PHACOC`

|ResourceRelationship
.2+|Recommended
|term:dwc[dwc:relationshipOfResource]
|`visits flowers of`

|ResourceRelationship
|term:dwc[dwc:relationshipOfResourceID]
|`http://purl.obolibrary.org/obo/RO_0002622`
|===

*An occurrence with a material sample* 

The table below highlights an example from the dataset https://doi.org/10.15468/g3bard[University of Michigan Museum of Zoology, Division of Reptiles & Amphibians] published by University of Michigan Museum of Zoology. In this example, a skin sample from a female toad of _Bufo americanus_ is preserved at the University of Michigan Museum of Zoology along with other body parts.

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Table |Recommended usage |Term |Example entry
|Occurrence
.3+|Required
|term:dwc[dwc:occurrenceID]
|`3df9bda0-c41a-4130-83bf-8603ae9c22bb`

|ResourceRelationship
|term:dwc[dwc:resourceID]
|`3df9bda0-c41a-4130-83bf-8603ae9c22bb`

|ResourceRelationship
|term:dwc[dwc:relatedResourceID]
|`urn:catalog:UMMZ:Herps:22`

|ResourceRelationship
.2+|Recommended
|term:dwc[dwc:relationshipEsetablishedDate]
|`2019-01-14`

|ResourceRelationship
|term:dwc[dwc:relationshipAccordingTo]
|`VertNet`
|===

<<<
