== Mapping occurrence information

[IMPORTANT]
====
Occurrence information should be saved to a DWC-A occurrence file. 
For example, see the `https://docs.google.com/spreadsheets/d/1A5wvy-zK7zl2eL79QOeADkbtPQXQtHUl/edit?gid=885414781#gid=885414781[occurrence]` tab in the data mapping template.
====

Organismal occurrence information is mapped and linked to a survey event
using the DwC Occurrence extension
(https://rs.gbif.org/core/dwc_occurrence_2024-02-23.xml[https://rs.gbif.org/core/dwc_occurrence_2024-02-23.xml]).
Occurrences can be mapped to only a single survey Event, however they
can link to any event level. In the case of a nested hierarchy, the best
practice recommendation is to link occurrence information to the lowest
possible event level to maintain specificity. Occurrence information
should be contained as a table in the Occurrence file of the DwC-A.

Each organism occurrence must include the following information:

* *Event ID:* A link the occurrence to the correct survey event with
term:dwc[dwc:eventID]. +
* *Occurrence ID:* A unique
term:dwc[dwc:occurrenceID]. +
* *Scientific name:* The most specific taxonomic identification of the
organism in
term:dwc[dwc:scientificName]. +
* *Basis of record:* The nature of the occurrence (e.g. human
observation, material specimen) must be reported in
term:dwc[dwc:basisOfRecord].

*Reporting multiple individuals as a single occurrence*

If multiple individuals of the same taxonomic classification are
observed and no additional information about the organisms (e.g., life
stage, sex) is collected other than taxonomic identification, report as
a single occurrence (e.g., 1 row in the table), with the following
information:

* a unique term:dwc[dwc:occurrenceID] +
* taxonomic classification of the organisms reported in
term:dwc[dwc:scientificName] +
* the quantity and unit of organisms observed reported in the paired
terms
term:dwc[dwc:organismQuantity]
and
term:dwc[dwc:organismQuantityType]

For example, if 4 hooded crows (_Corvus cornix_) were observed, a single
occurrence with one unique
term:dwc[dwc:occurrenceID] should be
reported.

[width="99%",cols="<20%,<16%,<16%,<16%,16%,16%",options="header",]
|===
|term:dwc[dwc:eventID]
|term:dwc[dwc:occurrenceID]
|term:dwc[dwc:basisOfRecord]
|term:dwc[dwc:scientificName]
|term:dwc[dwc:organismQuantity]
|term:dwc[dwc:organismQuantityType]
|uniqueEventID
|uniqueObsID
|HumanObservation
|Corvus cornix
|4
|individuals
|===

*Reporting multiple individuals as multiple occurrences*

If multiple individuals of the same taxonomic classification are
observed

If multiple individuals of the same taxonomic classification are
observed and additional information about the organisms (e.g., life
stage, sex) is collected, then a unique occurrence (row in the table)
should exist for each unique suite of taxonomic identification-organism
traits should be created.

For example, if 1 adult male and 3 adult females Indian gharials
(_Gavialis gangeticus_) were observed alive, two occurrences, each with
a unique term:dwc[dwc:occurrenceID]
would be reported.

[width="99%",cols="<12%,<11%,<11%,<11%,11%,11%,11%,11%,11%",options="header",]
|===
|term:dwc[dwc:eventID]
|term:dwc[dwc:occurrenceID]
|term:dwc[dwc:basisOfRecord]
|term:dwc[dwc:scientificName]
|term:dwc[dwc:organismQuantity]
|term:dwc[dwc:organismQuantityType]
|term:dwc[dwc:sex]
|term:dwc[dwc:lifeStage]
|term:dwc[dwc:vitality]
|uniqueEventID-1 |uniqueObsID-1 |HumanObservation |Gavialis gangeticus
|1 |individuals |male |adult |alive

|uniqueEventID-1 |uniqueObsID-2 |HumanObservation |Gavialis gangeticus
|3 |individuals |female |adult |alive
|===

The table below outlines the minimum required and recommended terms as
well some of the more commonly used terms and their recommended usage.
However, Darwin Core includes many more terms. It is recommended that
you take some time to review the DwC quick reference guide
(https://dwc.tdwg.org/terms/) and to identify and include any and all
terms available that allow you to share the richest version of your data
possible. Sections that may be of particular interest:

* occurrence (https://dwc.tdwg.org/terms/#occurrence) +
* identification (https://dwc.tdwg.org/terms/#identification) +
* taxon (https://dwc.tdwg.org/terms/#taxon)

[caption=""]
.Species occurrence terms, their recommended usage (status), and example data entries.
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
.4+|Required
|term:dwc[dwc:eventID]
|`uniqueEventID-1`

|term:dwc[dwc:occurrenceID]
|`uniqueObsID-2`

|term:dwc[dwc:scientificName]
|`Gavialis gangeticus`

|term:dwc[dwc:basisOfRecord]
|`HumanObservation`

.5+|Recommended
|term:dwc[dwc:taxonRank]
|`species`

|term:dwc[dwc:kingdom]
|`Animalia`

|term:dwc[dwc:organismQuantity]
|`3`

|term:dwc[dwc:organismQuantityType]
|`individuals`

|term:dwc[dwc:occurrenceStatus]
|`present` or `absent`

.6+|Share if available
|term:dwc[dwc:vernacularName]
|`Indian gharial`

|term:dwc[dwc:sex]
|`female`

|term:dwc[dwc:lifeStage]
|`adult`

|term:dwc[dwc:establishmentMeans]
|`native`

|term:dwc[dwc:degreeOfEstablishment]_
|`native`

|term:dwc[dwc:vitality]
|`dead`
|===

=== Reporting absences

*Absences* are defined here as the lack of detection of organisms
explicitly stated as part of the target taxonomic scope. To document
absences:

* In the *_Occurrence table_*:
** For each occurrence to be reported absent, the field
term:dwc[dwc:occurrenceStatus]
should be populated as `absent`:

term:dwc[dwc:occurrenceStatus] =
`absent`

* Recommended best practice is to also populate
term:dwc[dwc:individualCount] and
term:dwc[dwc:organismQuantity]
as `0` and term:dwc[dwc:organismQuantityType] as `Individuals`. +
* In the *_Event table_*:
** If one or more absences are reported at any taxonomic level
(term:dwc[dwc:occurrenceStatus] =
`absent`), then term:eco[eco:isAbsenceReported] for parent Events at all relevant levels should be populated as `true`

term:eco[eco:isAbsenceReported] = `true`

* A list of absent taxa can be provided using term:eco[eco:absentTaxa] at all relevant levels.

Absences should only be reported for taxa within the stated taxonomic
and/or organismal scope of a survey. Absence cannot be asserted for
bycatch.

[caption=""]
.Terms to indicate absence, or non-detection, and their recommendation usage.
[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Table |Recommended usage |Term |Example entry
|Occurrence
|Required
|term:dwc[dwc:occurrenceStatus]
|`present` or `absent`

|Occurrence
.4+|Recommended
|term:dwc[dwc:individualCount]
|`3`

|Occurrence
|term:dwc[dwc:organismQuantity]
|`3`

|Occurrence
|term:dwc[dwc:organismQuantityType]
|`individuals`

|Event
|term:eco[eco:isAbsenceReported]
|`true` or `false`

|Event
|Share if available
|term:eco[eco:absentTaxa]
|
|===

=== Abundance information

To capture abundance information in a dataset or at a specific event
level:

* In the *Occurrence table*, use the paired terms
term:dwc[dwc:organismQuantity] and term:dwc[dwc:organismQuantityType]
to report the observed abundance for each reported occurrence. For
example, if three individuals of a species were observed, the paired terms
would be populated as follows:
** term:dwc[dwc:organismQuantity] = `3` +
** term:dwc[dwc:organismQuantityType] = `Individuals` +
* In the *Event table*:
** The inclusion of abundance information in the dataset should be
indicated by populating term:eco[eco:isAbundanceReported] as `true`. +
** If an abundance cap, and what that cap was reported, this should be
captured using term:eco[eco:isAbundanceCapReported] and term:eco[eco:abundanceCap].

If the dataset or relevant event does not include abundance information
is not included in the dataset, then it is recommended that the
following terms be populated as follows in the *Event table*:

* term:eco[eco:isAbundanceReported] = `false` +
* term:eco[eco:isAbundanceCapReported] = `false`

[caption=""]
.Terms to indicate abundance, the table on which they should be provided, and their recommendation usage.
[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Table |Recommended usage |Term |Example entry
|Occurrence
.5+|Recommended
|term:dwc[dwc:individualCount]
|`3`

|Occurrence
|term:dwc[dwc:organismQuantity]
|`3`

|Occurrence
|term:dwc[dwc:organismQuantityType]
|`individuals`

|Event
|term:eco[eco:isAbundanceReported]
|`true` or `false`

|Event
|term:eco[eco:isAbundanceCapReported]
|`true` or `false`

|Event
|Share if available
|term:eco[ecoabundanceCap]
|`5`
|===

=== Species’ co-occurrence and species’ interactions

The Resource Relationship extension
(https://rs.gbif.org/extension/resource_relationship_2024-02-19.xml) can
be used to link information related across multiple occurrences (may be
from the same or from different events), such as:

* an occurrence with another occurrence +
* an occurrence with a material sample +
* a material sample with another material sample

[NOTE]
.*Using the Resource Relationship extension* (https://rs.gbif.org/extension/resource_relationship_2024-02-19.xml)
===
- Create a new `resourceRelationship` table
- Add term:dwc[dwc:eventID] as a column header so to link the record to the `Event` table.
- Add the Resource relationship extension fields as column headers. 
- For each related set of information,…
====
