== Additional guidance and reaching out for assistance

Need more information? Check out the following documentation:

* https://eco.tdwg.org/[Humboldt extension for ecological inventories] +
* https://techdocs.gbif.org/en/[GBIF Technical Documents] +
* https://manual.obis.org/[The OBIS Manual]

For any remaining questions, reach out for assistance from:

* The https://github.com/tdwg/hc[Humboldt Extension GitHub repository^]: questions about usage, issues with the vocabulary, and recommendations for new terms should be reported as an issue. +
* The https://discourse.gbif.org/[GBIF community forum^]. +
* The GBIF Node for your country or organization.
** If your country or organization is a member of GBIF and has an established Node, you can reach out directly to them.
*** If you’re uncertain if your country or organization is part of the GBIF network you can https://www.gbif.org/the-gbif-network[search here^]. +
** If your country or organization is not a member of GBIF, reach out to the mailto:helpdesk@gbif.org[GBIF helpdesk^] for assistance. +
* GBIF help desk
** In case technical documentation needs improvements, create an issue on the https://techdocs.gbif.org/en/[GitHub tech-docs project^]. +
** Send an email to the mailto:helpdesk@gbif.org[GBIF helpdesk]. 


== Feedback

The authors appreciate every opportunity to improve the guide. Feedback should be submitted as a GitHub issue. If you are unfamiliar of the with this process, refer to the instructions below: 

* Create a GitHub account (see https://www.vimeo.com/430640810[video how-to^]).
* If you see something, say something, by creating or commenting on issues on GitHub (see https://vimeo.com/430632177[video how-to^]). Please refer to specific sections or lines in your recommendations.

Please remember that all interactions within this process must adhere to the GBIF Code of Conduct, which aims to encourage a "safe, hospitable, and productive environment" that is "professional, respectful and harassment-free for all participating."

<<<
